import { creatorContracts } from "./creator-contracts";
import { endingContracts } from "./ending-contracts";
import { importContracts } from "./import-contracts";
import { getActionCapabilities } from "../actions/capabilities";
import { navigationContracts, immersiveHeroContracts } from "./navigation-hero-contracts";
import { evidenceContracts } from "./evidence-contracts";
import { commerceContracts } from "./commerce-contracts";
import { serviceContracts } from "./service-contracts";
import { collectionContracts } from "./collection-contracts";
import { artIds, typographyIds, type SectionId } from "./schemas";
import type { SectionContract } from "./contracts";

const base = {
  typography: { profiles: typographyIds, roles: ["display", "heading", "body", "accent", "mono"], behavior: "Semantic roles inherit; structural measures cap display scale without changing font relationships." },
  artDirections: artIds, artBehavior: "Art direction changes rhythm, gaps, framing and actions where consumed. Structural geometry and alignment stay section-owned.", motionIntensities: ["none", "restrained", "expressive"], overrides: ["typography", "artDirection", "motion"], icons: ["arrow-up-right"],
  responsive: { desktop: "Retain declared composition.", tablet: "Reduce gaps and preserve readable measures.", mobile: "Stack in semantic reading order; controls remain at least 44px.", readingOrder: ["heading", "context", "action"] },
  accessibility: { landmark: "section", heading: "h1", keyboard: "Native links and controls.", reducedMotion: "Complete resting state; no essential information hidden.", contrast: "Client tokens require contrast review; text remains on a solid surface." },
} as const;
const image = (geometries: NonNullable<SectionContract["media"]>["geometries"]) => ({ geometries, tones: ["natural", "monochrome", "high-contrast"] as const });
const nav = { ...base, category: "navigation", contentSchema: "navigation", mediaSchema: null, media: null, motion: ["none"], motionIntensities: ["none"], overrides: ["artDirection"], icons: ["menu", "close"],
  typography: { ...base.typography, roles: ["heading", "body", "accent", "mono"], behavior: "Brand, destinations and controls inherit semantic roles without replacing navigation behavior." },
  responsive: { ...base.responsive, readingOrder: ["brand", "destinations", "action"] },
  accessibility: { ...base.accessibility, landmark: "navigation", heading: null },
} as const;
const hero = { ...base, category: "hero", compatibility: { hero: { surface: "surface", overlaySafeZone: false } } } as const;
const body = { ...base, usage: "section-oriented", contentConstraints: "See executable strict content schema for item and text bounds.", mediaRequirements: "Authored media only where the schema requires it.", category: "storytelling", motion: ["none"], motionIntensities: ["none"], overrides: ["typography", "artDirection"], icons: [], compatibility: {},
  accessibility: { ...base.accessibility, heading: "h2", keyboard: "Static semantic reading surface; no fake controls.", reducedMotion: "Complete static composition; no motion at any intensity." },
} as const;
/** Standard serializable contracts shared by registry, validator, renderer and controls. */
const authoredSectionContracts = {
  ...creatorContracts,
  ...endingContracts,
  ...importContracts,
  ...navigationContracts,
  ...immersiveHeroContracts,
  ...collectionContracts,
  ...serviceContracts,
  ...commerceContracts,
  ...evidenceContracts,
  "navigation.primary": { ...nav, structuralDNA: "Full-width brand and one-level responsive disclosure.", variants: ["compact", "comfortable"], compatibility: { navigation: { placements: ["in-flow"], covers: ["surface"] } } },
  "navigation.island": { ...nav, artDirectionChoices: { center: ["publication", "precision", "billboard", "gallery"], end: ["publication", "precision", "billboard", "gallery", "salon"] }, artBehavior: "The island silhouette stays rounded. Art changes its border and open-panel corners; open the menu to inspect them. Center fixes margins: Gallery/Salon are equivalent. Publication/Runway are equivalent here. Global choices remain independent.", structuralDNA: "N01: compact opaque rounded island and anchored nonmodal panel.", variants: ["center", "end"], compatibility: { navigation: { placements: ["in-flow", "overlay"], covers: ["surface", "light-media", "dark-media"] } }, accessibility: { ...nav.accessibility, keyboard: "Escape and outside dismissal; focus leaves freely and returns to trigger on Escape." } },
  "navigation.contents": { ...nav, contentSchema: "navigation-contents", structuralDNA: "N02: sparse resting header; modal contents sheet with optional editorial note.", variants: ["numbered", "plain"], compatibility: { navigation: { placements: ["in-flow"], covers: ["surface"] } }, accessibility: { ...nav.accessibility, keyboard: "Native modal dialog: focus containment, inert background, Escape, close and restoration." } },
  "hero.statement": { ...hero, contentSchema: "statement", mediaSchema: null, media: null, structuralDNA: "Single typographic statement with supporting actions.", variants: ["start", "center"], motion: ["none", "fade"] },
  "hero.object-study": { ...hero, usage: "section-oriented", contentSchema: "object-study-introduction", mediaSchema: "single-image", media: image(["portrait-emphasis"]), structuralDNA: "H09: contextual copy and material note flank one rounded object plate; an optional object reference lives outside the image.", contentConstraints: "One image; category/reference <=80, title <=180, optional description <=400, material note <=180, optional object number <=12. Optional client action.", mediaRequirements: "One image with intrinsic dimensions, nonempty alt and authored focal/mobile crop; rounded well is structural.", itemRange: { min: 1, max: 1, unit: "object image" }, variants: ["object-study"], motion: ["none"], motionIntensities: ["none"], overrides: ["typography", "artDirection"], icons: [], artDirections: ["gallery", "salon", "precision"], artBehavior: "Spacing, plate inset/width, action shape and rounded frame radius change; rounding and contextual placement remain structural.", compatibility: { hero: { surface: "surface", overlaySafeZone: false }, flow: { surface: "inherited", bleed: "inset", scrolling: "document", sticky: false, density: "open" } }, responsive: { desktop: "Context lane, broad rounded object plate, outer object reference.", tablet: "Bound title scale and narrower gutters retain the three lanes.", mobile: "Context and action first, then rounded object plate with its reference in the outer margin.", readingOrder: ["category", "reference", "eyebrow", "title", "description", "material-note", "action", "image", "object-number"] }, accessibility: { ...base.accessibility, keyboard: "Optional native client action; no decorative selection or pointer-only controls.", reducedMotion: "Always static at every site intensity." } },
  "hero.vertical-record": { ...hero, usage: "section-oriented", contentSchema: "vertical-record-introduction", mediaSchema: "single-image", media: image(["portrait-emphasis"]), structuralDNA: "H16: central image spine spans context and copy, while a separate dated record establishes continuity; optional left-to-middle reveal animates the image only.", contentConstraints: "One image; 2–5 uniquely identified dated records, date label <=40, record text <=100, title <=180, optional description <=400. One client action.", mediaRequirements: "One crop-ready image with intrinsic dimensions, nonempty alt and authored focal/mobile position; central portrait spine remains rectangular.", itemRange: { min: 2, max: 5, unit: "dated records" }, variants: ["vertical-record"], motion: ["none", "media-reveal"], artDirections: ["runway", "publication", "gallery", "precision"], artBehavior: "Gutters, pauses, record intervals/rule weight and action shape change; central image axis and record lane stay fixed.", compatibility: { hero: { surface: "surface", overlaySafeZone: false }, flow: { surface: "inherited", bleed: "inset", scrolling: "document", sticky: false, density: "open" } }, responsive: { desktop: "Copy at left, full-height central media spine, dated record at right.", tablet: "Compact column gaps retain the spine and record relationship.", mobile: "Context/copy/action precede the image and record lanes, which remain adjacent.", readingOrder: ["category", "reference", "eyebrow", "title", "description", "action", "image", "record-label", "dated-records"] }, accessibility: { ...base.accessibility, keyboard: "Native client action; labelled aside and ordered record. No autoplay or fake timeline navigation.", reducedMotion: "Image is immediately complete under OS reduce or site none; records and copy always remain static." } },
  "hero.front-page": { ...hero, contentSchema: "front-page", mediaSchema: "single-image", media: image(["editorial-crop", "framed"]), structuralDNA: "H17: publication masthead above unequal headline / scene / abstract spread.", variants: ["spread", "lead-story"], motion: ["none", "media-reveal"], responsive: { ...base.responsive, mobile: "Masthead then headline, image and marginal abstract.", readingOrder: ["edition", "masthead", "headline", "action", "scene", "abstract"] } },
  "hero.open-circuit": { ...hero, contentSchema: "signal-introduction", mediaSchema: "signal-data", media: null, structuralDNA: "H18: one real or explicitly illustrative signal plot and baseline readout.", variants: ["baseline", "annotated"], motion: ["none"], motionIntensities: ["none"], overrides: ["typography", "artDirection"], artDirections: ["precision", "publication", "billboard"], responsive: { ...base.responsive, readingOrder: ["headline", "context", "signal", "readout", "source", "action"] } },
  "hero.between-acts": { ...hero, contentSchema: "bookends", mediaSchema: "single-image", media: image(["panorama", "editorial-crop", "full-bleed"]), structuralDNA: "H22: two typographic bookends around an interrupted low media ribbon.", variants: ["interval", "extended-pause"], motion: ["none", "media-reveal"], artDirections: ["runway", "gallery", "publication", "salon"], responsive: { ...base.responsive, readingOrder: ["opening-phrase", "side-note", "ribbon", "closing-phrase", "context", "action"] } },
  "hero.assembly": { ...hero, contentSchema: "assembly-introduction", mediaSchema: "assembly-parts", media: null, structuralDNA: "H24: stacked promise faces an exploded parts diagram and specification joint.", variants: ["exploded", "compact"], motion: ["none", "fade"], artDirections: ["billboard", "precision", "publication"], responsive: { ...base.responsive, readingOrder: ["headline", "context", "parts", "specifications", "action"] } },
  "hero.comparison": { ...hero, contentSchema: "comparison-introduction", mediaSchema: "registered-image-pair", media: image(["full-bleed"]), configuration:[{name:"contentAlignment",options:["left","center","right"]}], structuralDNA: "H12 v1: matched visual states divided by a visitor-controlled seam, with a compact 22rem context panel independently placed left/center/right.", variants: ["balanced", "inspection"], motion: ["none"], motionIntensities: ["none"], overrides: ["typography", "artDirection"], compatibility: { hero: { surface: "dark-media", overlaySafeZone: true } }, responsive: { ...base.responsive, readingOrder: ["comparison", "headline", "summary", "state-controls", "action"] }, accessibility: { ...base.accessibility, keyboard: "Native range plus step/reset buttons; labels describe both states. Compact context panel supports independent left, center or right placement.", contrast: "Opaque content and navigation plates; no text on unclassified imagery." } },
  "content.feature-list": { ...base, category: "content", contentSchema: "features", mediaSchema: null, media: null, structuralDNA: "Existing feature collection in grid or list flow.", variants: ["grid", "list"], motion: ["none", "stagger"], icons: [], compatibility: {}, accessibility: { ...base.accessibility, heading: "h2" } },
  "story.object-biography": { ...body, contentSchema: "object-biography", mediaSchema: "single-image", media: image(["contained", "portrait-emphasis", "framed"]), structuralDNA: "S01: central artifact dossier with three numbered observations and an origin-to-continuation closing line.", variants: ["annotated", "reading-room"], artDirections: ["publication", "gallery", "precision", "runway"], artBehavior: "Rhythm, record gaps, rules and framed-media radius vary. Artifact/records/closing hierarchy is protected.", responsive: { ...base.responsive, desktop: "Central image with records in an offset side lane; reading-room places records beneath the image.", tablet: "Narrower two-column dossier retains record measure.", mobile: "Single continuous reading column.", readingOrder: ["title", "introduction", "subject", "image", "records", "origin", "continuation"] } },
  "story.working-conversation": { ...body, contentSchema: "working-conversation", mediaSchema: null, media: null, structuralDNA: "S03: successive questions and attributed answers in an offset transcript lane, retaining turn-taking.", variants: ["transcript", "roundtable"], artDirections: ["salon", "publication", "precision", "gallery"], artBehavior: "Question/answer intervals and transcript gutters change. Every question precedes its attributed answer.", responsive: { ...base.responsive, desktop: "Question followed by speaker gutter and offset answer; roundtable aligns question beside the response.", tablet: "Transcript retains the speaker gutter; roundtable stacks each exchange.", mobile: "Question, speaker, role, answer, note; repeat.", readingOrder: ["title", "introduction", "attribution", "question", "speaker", "role", "answer", "note"] } },
  "story.decision-ledger": { ...body, icons: ["plus"], contentSchema: "decision-ledger", mediaSchema: null, media: null, structuralDNA: "S06: continuous ledger binding principle, tension and practice, with rationale attached to its decision.", variants: ["open", "disclosure"], artDirections: ["precision", "publication", "billboard"], artBehavior: "Ledger padding, gutter and rule weight vary; the three comparison dimensions remain fixed.", responsive: { ...base.responsive, desktop: "Three aligned comparison columns with rationale beneath each decision.", tablet: "Three columns with bounded measures.", mobile: "Numbered decision: principle, tension, practice, rationale. Column labels repeat visibly.", readingOrder: ["title", "introduction", "principle", "tension", "practice", "rationale"] }, accessibility: { ...body.accessibility, keyboard: "Disclosure variant uses native details/summary: Tab focus, Enter/Space toggle. Open variant has no interaction." } },
} as const satisfies Record<SectionId, SectionContract>;

export const sectionContracts = Object.fromEntries(Object.entries(authoredSectionContracts).map(([id, contract]) => [id, "actions" in contract ? contract : { ...contract, actions: getActionCapabilities(id) }])) as Record<SectionId, SectionContract>;

export function getSectionContract(id: SectionId): SectionContract { return sectionContracts[id]; }
