import type { SectionContract } from "./contracts";
import type { CreatorSectionId } from "./creator-schemas";
import { getActionCapabilities } from "../actions/capabilities";
const base = {
  usage: "section-and-page-capable", mediaSchema: null, media: null,
  typography: { profiles: ["editorial", "luxury", "neo-grotesk", "geometric", "poster", "humanist", "technical", "brutalist", "playful", "fashion"], roles: ["heading", "body", "accent", "mono"], behavior: "Inherits semantic client fonts with fluid headings, wrapping and readable paragraph measures." },
  artDirections: ["gallery", "publication", "precision", "billboard", "salon", "runway"], artBehavior: "Client tokens determine spacing, borders, colors and action treatment; layout and photo styling are independently configurable.",
  motion: ["none"], motionIntensities: ["none"], overrides: ["typography", "artDirection"], icons: ["arrow-up-right"],
  compatibility: { flow: { surface: "inherited", bleed: "inset", scrolling: "document", sticky: false } },
  responsive: { desktop: "Authored layout with bounded copy and flexible records.", tablet: "Fluid gaps and wrapping retain every record.", mobile: "One-column reading order, wrapping links and 44px link targets.", readingOrder: ["heading", "context", "records", "actions"] },
  accessibility: { landmark: "section", heading: "h2", keyboard: "Native links with visible keyboard focus.", reducedMotion: "Static content at every motion setting.", contrast: "Semantic client surfaces and foreground; no copy overlays on photographs." },
} as const;
const shared = [{ name: "density", options: ["open", "compact"] }, { name: "surface", options: ["transparent", "surface", "framed"] }, { name: "alignment", options: ["left", "center", "right"] }] as const;
export const creatorContracts = {
  "proof.social-reach": { ...base, actions: getActionCapabilities("proof.social-reach"), category: "proof", contentSchema: "proof.social-reach", structuralDNA: "A personal audience statement, editable following/views/reach metrics and real social profile links; cards, editorial rules or a compact media-kit row.", variants: ["cards", "editorial", "compact"], configuration: [...shared, { name: "statsStyle", options: ["bold", "quiet"] }, { name: "linkStyle", options: ["pills", "rows", "icons", "icon-label", "handles", "cards"] }], itemRange: { min: 1, max: 8, unit: "metrics and profiles" }, contentConstraints: "1–8 unique stats and 1–8 unique profiles; values, labels, periods, handles and optional measurement sources are client-authored.", mediaRequirements: "No image required.", interactionCapabilities: ["social-profile-links", "metric-source-links", "section-action"], evidence: { model: "Client-authored audience metrics", scale: "small", integrity: "Demo metrics are labelled illustrative. Clients supply their actual analytics, time windows and optional sources." } },
  "about.creator-profile": { ...base, actions: getActionCapabilities("about.creator-profile"), category: "about", contentSchema: "about.creator-profile", mediaSchema: "creator-portraits", structuralDNA: "A personal introduction pairs an everyday photograph with a biography, interest tags, optional second snapshot and signature; scrapbook, split or centered layouts.", variants: ["scrapbook", "split", "centered"], configuration: [...shared, { name: "imageSide", options: ["left", "right"] }, { name: "photoStyle", options: ["snapshot", "clean"] }, { name: "imageShape", options: ["portrait", "square", "rounded"] }, { name: "interestShape", options: ["square", "soft", "rounded", "pill"] }], itemRange: { min: 0, max: 8, unit: "interests" }, contentConstraints: "Biography up to 2400 characters, optional role/location/signature and up to eight unique interests.", mediaRequirements: "One authored image with intrinsic dimensions and alt; optional secondary candid photograph. Editor supports replacement and focal points.", interactionCapabilities: ["section-action"] },
} as const satisfies Record<CreatorSectionId, SectionContract>;
