import type { SectionContract } from "./contracts";
import { getActionCapabilities } from "../actions/capabilities";
import type { EndingSectionId } from "./ending-schemas";
const base = {
  contentSchema:"ending-content", mediaSchema:"optional-authored-image", media:null,
  typography:{profiles:["editorial","luxury","neo-grotesk","geometric","poster","humanist","technical","brutalist","playful","fashion"],roles:["display","heading","body","accent","mono"],behavior:"Client type roles, bounded heading scales and authored text measures; no imported font or brand."},
  artDirections:["gallery","publication","precision","billboard","salon","runway"],artBehavior:"Semantic color, gutter, rhythm, rules, corners and actions follow client art tokens; the source structure remains intact.",
  motionIntensities:["none","restrained","expressive"],overrides:["typography","artDirection","motion"],icons:["arrow-up-right"],motion:["none","fade"],
  contentConstraints:"Strict bounded content and unique stable record IDs. All destinations use typed Actions; forms declare a real submission boundary.",
  mediaRequirements:"Optional client logo/image uses intrinsic dimensions and accessible alt; image records support authored focal/mobile crops.",
  compatibility:{flow:{surface:"inherited",bleed:"inset",scrolling:"document",sticky:false}},
  responsive:{desktop:"Retain distinct structural lanes and semantic reading order.",tablet:"Contract lanes and gaps; wrap long copy and actions.",mobile:"Authored single-column reading, two-column sitemap groups, 44px controls; narrow fields/actions stack.",readingOrder:["brand-or-heading","context","actions","destinations","form","legal"]},
  accessibility:{landmark:"section",heading:"h2",keyboard:"Native links, labelled fields and named controls with visible focus; no hover-only access.",reducedMotion:"Static complete composition; no automatic advance or hidden essential content.",contrast:"Reading copy uses opaque semantic surfaces. Client color tokens require contrast review."},
} as const;
const spacing = [{name:"density",options:["compact","open"]},{name:"surface",options:["transparent","surface","brand"]}] as const;
const ending = [...spacing,{name:"measure",options:["reading","wide"]}] as const;
const footer = {...base,category:"footer",usage:"global-site-component",footer:{navigationDepth:"configurable",sitemap:true,social:true,contact:true,newsletter:false,globalSite:true},accessibility:{...base.accessibility,landmark:"footer",heading:null},configuration:[...ending,{name:"navigationDepth",options:["top-level","two-level","all"]}]} as const;
const gallery = {...base,category:"portfolio",usage:"section-and-page-capable",motion:["none","depth-shift"],configuration:spacing,itemRange:{min:2,max:16,unit:"authored images"},responsive:{...base.responsive,readingOrder:["heading","context","actions","selection","record","item-action"]}} as const;
export const endingContracts = {
  "cta.editorial":{...base,category:"cta",usage:"section-oriented",actions:getActionCapabilities("cta.editorial"),structuralDNA:"Minimal measured proposition with primary and optional secondary actions; independent left, center or right placement.",variants:["left","center","right"],configuration:ending},
  "cta.signal":{...base,category:"cta",usage:"section-oriented",actions:getActionCapabilities("cta.signal"),structuralDNA:"Bold conversion poster or reversible copy/media split; optional full viewport presence with an opaque action field.",variants:["poster","split","reverse"],configuration:[...ending,{name:"height",options:["section","viewport"]}]},
  "contact.inquiry":{...base,category:"contact",usage:"section-and-page-capable",actions:getActionCapabilities("contact.inquiry"),contact:{modes:["information","split","social"],form:true,booking:true,social:true,submission:"host-or-email-draft"},structuralDNA:"Direct contact discovery, a paired inquiry form, or social-first directory with optional booking/management/media-kit actions.",variants:["information","split","social"],configuration:ending},
  "footer.sitemap":{...footer,actions:getActionCapabilities("footer.sitemap"),structuralDNA:"Brand statement and social discovery beside or above a real site sitemap, ending with a legal/copyright rail.",variants:["brand-left","brand-above"]},
  "footer.compact":{...footer,actions:getActionCapabilities("footer.compact"),footer:{...footer.footer,navigationDepth:"top-level"},structuralDNA:"Compact brand, flat destination row and social/legal close; centered stack or horizontal brand rail.",variants:["center","row"],configuration:ending},
  "footer.split":{...footer,actions:getActionCapabilities("footer.split"),footer:{...footer.footer,newsletter:true},structuralDNA:"Contrasting brand/CTA card beside a sitemap/newsletter card; reversible card order.",variants:["brand-left","brand-right"]},
  "footer.banner":{...footer,actions:getActionCapabilities("footer.banner"),footer:{...footer.footer,newsletter:true},structuralDNA:"Large brand-colored typographic banner above newsletter/social discovery and sitemap columns.",variants:["center","left"]},
  "work.expand-rail":{...gallery,actions:getActionCapabilities("work.expand-rail"),structuralDNA:"A selected image opens between vertical label rails or image strips; mobile becomes an accessible labelled accordion.",variants:["label-rails","image-strips"],configuration:[...spacing,{name:"height",options:["portrait","landscape"]},{name:"railWidth",options:["compact","comfortable"]}],interactionCapabilities:["mouse-preview","keyboard-selection","touch-selection","item-destinations"]},
  "work.card-rail":{...gallery,actions:getActionCapabilities("work.card-rail"),structuralDNA:"Native scroll-snap editorial card strip or centered perspective carousel; optional category filtering and full-image dialog stay separate from destinations.",variants:["cards","coverflow"],configuration:[...spacing,{name:"ratio",options:["portrait","square","landscape"]},{name:"filter",options:["none","category"]},{name:"inspection",options:["none","dialog"]}],interactionCapabilities:["native-swipe","named-step-controls","category-filter","native-dialog","item-destinations"]},
  "work.glass-lens":{...gallery,actions:getActionCapabilities("work.glass-lens"),structuralDNA:"An image ribbon moves beneath a fixed rounded refracting lens; explicit selection and a canonical record preserve access without a perpetual render loop.",variants:["portrait","landscape"],configuration:[...spacing,{name:"lens",options:["subtle","strong"]}],interactionCapabilities:["named-selection","lens-inspection","item-destinations"]},
} as const satisfies Record<EndingSectionId,SectionContract>;
