import type { SectionContract } from "./contracts";
import { getActionCapabilities } from "../actions/capabilities";
import type { ImportSectionId } from "./import-schemas";
const base = {
 usage:"section-and-page-capable",mediaSchema:"authored-image-records",contentConstraints:"Strict text and item bounds, unique stable IDs; see executable schema.",mediaRequirements:"Intrinsic dimensions, nonempty alt, focal/mobile sources; dedicated thumbnails for more than eight images.",
 typography:{profiles:["editorial","luxury","neo-grotesk","geometric","poster","humanist","technical","brutalist","playful","fashion"],roles:["display","heading","body","accent","mono"],behavior:"Semantic roles inherit the client profile; bounded fluid headings and wrapping maintain the composition."},
 artDirections:["gallery","publication","precision","billboard","salon","runway"],artBehavior:"Art tokens control spacing, rule weight, framing and action treatments; the mechanism retains its authored geometry.",motionIntensities:["none","restrained","expressive"],overrides:["typography","artDirection","motion"],media:null,icons:["arrow-up-right"],
 responsive:{desktop:"Authored composition.",tablet:"Contract gaps and typography without clipping content.",mobile:"Complete canonical reading view and 44px controls.",readingOrder:["heading","context","actions","media","records"]},
 accessibility:{landmark:"section",heading:"h2",keyboard:"Native controls and links with visible focus; canonical content remains available.",reducedMotion:"Complete static reading view; no autoplay or hidden essential content.",contrast:"Solid semantic surfaces behind text; client tokens require contrast review."},
} as const;
export const importContracts = {
 "hero.image-marquee":{...base,actions:getActionCapabilities("hero.image-marquee"),category:"hero",contentSchema:"hero.image-marquee",structuralDNA:"Centered or start-aligned proposition above a continuous tilted image ribbon; copy and optional actions occupy their own opaque reading field.",variants:["center","start"],configuration:[{name:"direction",options:["left","right"]},{name:"speed",options:["slow","medium","fast"]},{name:"tilt",options:["flat","alternating"]},{name:"ratio",options:["portrait","square","landscape"]},{name:"surface",options:["transparent","surface","framed"]}],motion:["none","marquee"],itemRange:{min:3,max:16,unit:"images"},interactionCapabilities:["pause","still-reading","item-destinations"],compatibility:{hero:{surface:"surface",overlaySafeZone:false},flow:{surface:"inherited",bleed:"inset",scrolling:"document",sticky:false}},accessibility:{...base.accessibility,heading:"h1"}},
 "story.process-timeline":{...base,actions:getActionCapabilities("story.process-timeline"),category:"storytelling",contentSchema:"story.process-timeline",structuralDNA:"A scroll-driven pinned track connects an optional opening image to alternating labelled process stations, with a visible progress line; chronology stays in authored order.",variants:["alternating","above"],configuration:[{name:"density",options:["open","compact"]},{name:"surface",options:["transparent","surface","framed"]}],motion:["none","horizontal-scroll"],itemRange:{min:2,max:10,unit:"steps"},interactionCapabilities:["scroll-progression","all-steps-reading","step-destinations"],compatibility:{flow:{surface:"inherited",bleed:"inset",scrolling:"document",sticky:true}},responsive:{...base.responsive,desktop:"Sticky track advances according to measured overflow; alternating stems connect each process station.",mobile:"Vertical ordered timeline; no scroll interception, pinning or lateral motion."}},
 "work.image-sphere":{...base,actions:getActionCapabilities("work.image-sphere"),category:"portfolio",contentSchema:"work.image-sphere",structuralDNA:"A responsive image constellation rotates around a virtual sphere; drag, arrow controls and a complete contact list open a native spotlight dialog.",variants:["center","split"],configuration:[{name:"speed",options:["slow","medium","fast"]},{name:"direction",options:["left","right"]},{name:"shape",options:["circle","rounded"]},{name:"surface",options:["transparent","surface","framed"]}],motion:["none","depth-shift"],itemRange:{min:4,max:32,unit:"images"},interactionCapabilities:["pointer-drag","keyboard-rotation","pause","all-images-reading","native-spotlight-dialog","item-destinations"],compatibility:{flow:{surface:"inherited",bleed:"inset",scrolling:"document",sticky:false}}},
} as const satisfies Record<ImportSectionId,SectionContract>;
