"use client";
import { useState, type ReactNode } from "react";
import { LabEditor } from "../editor/LabEditor";
import { collection006Review, immersiveCreativeDirection } from "../../registry/creative-review";
import { serviceContexts } from "./fixtures";
import { serviceProposal, serviceStudies } from "./studies";
import { ServiceStudyPreview } from "./Study";

export function ServiceCollectionGallery({toolbar,workspaceSwitch}:{toolbar?:ReactNode;workspaceSwitch?:ReactNode}) {
 const [selected,setSelected]=useState("C01"),[adaptation,setAdaptation]=useState(0),[device,setDevice]=useState("desktop"),[overview,setOverview]=useState(false),[tab,setTab]=useState("study");
 const study=serviceStudies.find(s=>s.id===selected)!,context=serviceContexts[adaptation];
 const notes=[["Information model",study.dna],["Scale / usage",`${study.scale} · ${study.usage}`],["Content contract",study.content],["Media contract",study.media],["Implemented interaction",study.interaction],["Mobile art direction",study.mobile],["Proposed motion",study.motion],["Compatibility",study.compatibility],["Limits",study.limitations],["Authored typography / art",`${study.typography.join(" / ")} · ${study.art}`]];
 return <LabEditor title="Design Lab" toolbar={toolbar} workspaceSwitch={workspaceSwitch} canvasWidth={overview?1440:device==="mobile"?390:device==="tablet"?768:1440} resetKey={`${selected}-${adaptation}-${device}-${overview}`} activeTab={tab} onTabChange={setTab} tabs={[
 {id:"study",label:"Study",content:<><header className="calibration-intro"><h2>Collection 006 · Services / Capabilities</h2><p>All twelve creative studies approved by the user. C03 and C10 are particular favorites for image usage and animation potential. Production status remains separate.</p></header><div className="calibration-controls"><label>Service study<select aria-label="Service study" value={selected} disabled={overview} onChange={e=>setSelected(e.target.value)}>{serviceStudies.map(s=><option key={s.id} value={s.id}>{s.id} · {s.name}</option>)}</select></label><label>Client adaptation<select aria-label="Service client adaptation" value={adaptation} onChange={e=>setAdaptation(Number(e.target.value))}>{serviceContexts.map((b,i)=><option key={b.id} value={i}>{b.brand} · {b.context}</option>)}</select></label><label>Client artboard<select aria-label="Service client artboard" disabled={overview} value={device} onChange={e=>setDevice(e.target.value)}><option value="desktop">Desktop · 1440px</option><option value="tablet">Tablet · 768px</option><option value="mobile">Mobile · 390px</option></select></label><button type="button" aria-pressed={overview} onClick={()=>setOverview(v=>!v)}>{overview?"Return to selected study":"Compare twelve studies"}</button></div><div className="c6-notes"><h3>{study.name}</h3><p><strong>{collection006Review[study.id].status}</strong> · {collection006Review[study.id].note}</p><p>{study.family} · {study.scale}</p><p>{study.dna}</p><p>{study.interaction}</p><p>{study.typography[adaptation]} / {study.art} · Motion none. Links open local summary previews; no Service Detail pages have been built.</p></div></>},
 {id:"contract",label:"Contract",content:<div className="c6-notes"><h2>{study.id} · {study.name}</h2><dl>{notes.map(([name,value])=><div key={name}><dt>{name}</dt><dd>{value}</dd></div>)}</dl><p>Brand tokens inherit at the host boundary. Media and typography are authored for each adaptation; arbitrary overrides are not exposed. Creative direction is approved; compatibility remains a proposal until reusable implementation and Composition verification.</p><details><summary>Composition proposal contract</summary><pre style={{whiteSpace:"pre-wrap",fontSize:".7rem"}}>{JSON.stringify(serviceProposal(study),null,2)}</pre></details></div>},
 {id:"review",label:"Review",content:<div className="c6-notes"><h2>Review / Collection 006</h2><p>All twelve: Approved by the user on 1 October 2026. C03 and C10 are particular favorites. Earlier collections and their dispositions are preserved.</p><h3>Human creative direction</h3><p>{immersiveCreativeDirection}</p><h3>Original experimental shortlist (before human review)</h3>{serviceStudies.filter(s=>s.shortlist).map(s=><p key={s.id}><strong>{s.id} · {s.name}.</strong> {s.shortlist}</p>)}<h3>Anti-convergence findings</h3><p>C01/C04: open editorial scanning versus progressive scope disclosure. C03/C10: persistent capability directory versus paired case evidence. C07/C12: grouped phase responsibility versus selecting comparable engagement scopes. C05/C06: independent customer situations versus a dependent journey. C06/C08: visitor responsibilities versus internal system interfaces. C09 retains imagery as the entry point.</p><p>The full 66-pair comparison and content/media limits are in docs/design-engine/creative-collection-006. Human review is authoritative; the comparison is not a numerical approval score.</p><h3>Adaptations / evidence</h3><p>COMMON GROUND: architecture, warm paper and spatial photographs. RELAY / DATA: platform capabilities, dark technical surfaces and four authored explanatory diagrams. Gather school: cooking programs, warm humanist treatments and food/table imagery. The platform carries denser content in the index, desk and matrix.</p><p>Photographs reuse Collection 005 / Calibration 002 study assets with their existing provenance; no Scar references or design language. Diagrams are new native SVG illustrations. All brands and outcomes are fictional. C10 explicitly labels its plates illustrative, not measured results.</p><h3>Boundaries</h3><p>No registration, production promotion, pricing, Service Detail routes, full templates, page recipes or Motion Engine expansion. Current studies use motion none; future proposals reuse existing behaviors where suitable.</p></div>},
 ]}>{overview?<div className="c6-overview">{serviceStudies.map(s=><article key={s.id}><h3>{s.id} · {s.name}</h3><div className="c6-overview-stage" inert><ServiceStudyPreview study={s} context={context} adaptation={adaptation}/></div><button type="button" onClick={()=>{setSelected(s.id);setOverview(false);}}>Inspect {s.id} · {s.name} ↗</button></article>)}</div>:<ServiceStudyPreview study={study} context={context} adaptation={adaptation}/>}</LabEditor>;
}
