"use client";
/* eslint-disable @next/next/no-img-element -- Portable Lab studies retain authored intrinsic media dimensions. */
import { useEffect, useId, useRef, useState, type ReactNode } from "react";
import { DesignThemeProvider } from "../../foundations/DesignThemeProvider";
import { VigilIcon } from "../../icons/VigilIcon";
import type { FontBindings } from "../../foundations/typography/types";
import { serviceFixture, type ServiceContext } from "./fixtures";
import type { ServiceStudy } from "./studies";
import type { ServiceContent, StudyContent } from "./contracts";

type Plate = {src:string;alt:string;width:number;height:number};
function Picture({image}:{image:Plate}) {return <img src={image.src} alt={image.alt} width={image.width} height={image.height} loading="lazy" decoding="async"/>;}
const number=(i:number)=>String(i+1).padStart(2,"0");
function CapabilityMatrix({content,phase}:{content:StudyContent<"C07">;phase?:number}) {
 const columns=content.phases.map((label,index)=>({label,index})).filter(c=>phase===undefined||c.index===phase);
 return <table><caption>Capability coverage by delivery phase</caption><thead><tr><th scope="col">Discipline / capability</th>{columns.map(c=><th key={c.index} scope="col">{c.label}</th>)}</tr></thead>{content.groups.map(g=><tbody key={g.name}><tr className="c6-group-row"><th colSpan={columns.length+1} scope="rowgroup">{g.name}</th></tr>{g.capabilities.map(c=><tr key={c.id}><th scope="row">{c.title}</th>{columns.map(p=><td key={p.index} data-coverage={c.coverage[p.index]}>{c.coverage[p.index]}</td>)}</tr>)}</tbody>)}</table>;
}

export function ServiceStudyPreview({study,context,adaptation,fonts}:{study:ServiceStudy;context:ServiceContext;adaptation:number;fonts?:FontBindings}) {
 const [bg,fg,accent]=context.palette;
 return <DesignThemeProvider typography={study.typography[adaptation]} artDirection={study.art} motion="none" fonts={fonts} overrides={{color:{background:bg,surface:bg,surfaceElevated:bg,foreground:fg,muted:fg,accent,accentForeground:bg,border:fg}}}>
   <ServiceStudyArtwork key={`${study.id}-${context.id}`} model={serviceFixture(study.id,context)} />
 </DesignThemeProvider>;
}
export function ServiceStudyArtwork({model}:{model:ServiceContent}) {
 const [selected,setSelected]=useState(0),[phase,setPhase]=useState(0),[baseline,setBaseline]=useState(0),[candidate,setCandidate]=useState(1);
 const [detail,setDetail]=useState<{id:string;title:string;body:string}|null>(null);
 const detailHeading=useRef<HTMLHeadingElement>(null), returnLink=useRef<HTMLAnchorElement|null>(null);
 const uid=useId(), heading=`${uid}-title`;
 useEffect(()=>{if(detail)detailHeading.current?.focus();},[detail]);
 const link=(destination:{href:string;label:string},title:string,body:string)=><a className="c6-detail-link" href={destination.href} onClick={event=>{event.preventDefault();returnLink.current=event.currentTarget;setDetail({id:destination.href.slice(1),title,body});}}>{destination.label} <span aria-hidden="true">↗</span></a>;
 let artwork:ReactNode;
 switch(model.kind){
 case "C01": artwork=<ol className="c6-index">{model.content.entries.map((entry,i)=><li key={entry.id}><span className="c6-number">{number(i)}</span><div><h3>{entry.title}</h3><p>{entry.summary}</p>{link(entry.detail,entry.title,entry.summary)}</div><ul className="c6-deliverables">{entry.deliverables.map(d=><li key={d}>{d}</li>)}</ul></li>)}</ol>;break;
 case "C02": artwork=<div className="c6-manifesto"><p className="c6-promise">{model.content.promise}</p>{model.content.principles.map((p,i)=><article key={p.verb}><span className="c6-number">{number(i)}</span><h3>{p.verb}</h3><div><p>{p.pledge}</p><small>Boundary / {p.boundary}</small></div></article>)}</div>;break;
 case "C03": {const c=model.content.capabilities[selected];artwork=<div className="c6-desk"><div className="c6-directory" role="group" aria-label="Choose a capability">{model.content.capabilities.map((c,i)=><button type="button" key={c.id} aria-pressed={selected===i} aria-controls={`${uid}-evidence`} onClick={()=>setSelected(i)}><span className="c6-number">{number(i)}</span><span>{c.title}<small>{c.category}</small></span><span aria-hidden="true">↗</span></button>)}</div><article id={`${uid}-evidence`} className="c6-desk-evidence"><p className="c6-kicker" aria-live="polite">Selected capability / {c.title}</p><Picture image={c.image}/><div className="c6-desk-caption"><div><h3>{c.title}</h3><p>{c.description}</p></div><div><small>What this enables</small><p>{c.outcome}</p>{link(c.detail,c.title,c.description)}</div></div></article></div>;break;}
 case "C04": artwork=<div className="c6-disclosures">{model.content.services.map((s,i)=><details key={s.id}><summary><span className="c6-number">{number(i)}</span><span><strong>{s.title}</strong><span className="c6-row-summary">{s.summary}</span></span><VigilIcon name="chevron-down" decorative/></summary><div className="c6-disclosure-body"><div><h3>Within the scope</h3><ul>{s.included.map(item=><li key={item}>{item}</li>)}</ul></div><div><h3>Outside the scope</h3><p>{s.boundary}</p>{link(s.detail,s.title,s.summary)}</div></div></details>)}</div>;break;
 case "C05": artwork=<ol className="c6-situations">{model.content.situations.map((s,i)=><li key={s.need}><div className="c6-need"><small>{number(i)} / The friction</small><h3>{s.need}</h3></div><div className="c6-response"><small>The capability</small><p>{s.response}</p></div><div className="c6-outcome"><small>The possibility</small><p>{s.outcome}</p><small>{s.evidence}</small></div></li>)}</ol>;break;
 case "C06": artwork=<ol className="c6-journey">{model.content.stages.map((s,i)=><li key={s.id}><span className="c6-station">{number(i)}</span><article><p className="c6-kicker">With / {s.owner}</p><h3>{s.title}</h3><p>{s.work}</p><dl><div><dt>Arrive with</dt><dd>{s.input}</dd></div><div><dt>Leave with</dt><dd>{s.output}</dd></div></dl></article></li>)}</ol>;break;
 case "C07": artwork=<div className="c6-matrix"><label className="c6-mobile-only">Inspect delivery phase<select value={phase} onChange={e=>setPhase(Number(e.target.value))}>{model.content.phases.map((p,i)=><option key={p} value={i}>{p}</option>)}</select></label><p className="c6-legend">Lead = primary responsibility · Support = contributing responsibility · — = outside scope</p><div className="c6-desktop-only"><CapabilityMatrix content={model.content}/></div><div className="c6-mobile-only"><CapabilityMatrix content={model.content} phase={phase}/></div></div>;break;
 case "C08": artwork=<div className="c6-system"><div className="c6-terminal"><small>Input</small><p>{model.content.input}</p></div><ol>{model.content.layers.map((layer,i)=><li key={layer.id}><div className="c6-layer"><span className="c6-number">{number(i)}</span><div><h3>{layer.title}</h3><p>{layer.responsibility}</p></div><ul>{layer.components.map(c=><li key={c}>{c}</li>)}</ul></div><p className="c6-handoff"><span aria-hidden="true">↓</span> {layer.handoff}</p></li>)}</ol><div className="c6-terminal"><small>Output</small><p>{model.content.output}</p></div></div>;break;
 case "C09": artwork=<div className="c6-atlas">{model.content.plates.map((p,i)=><figure key={p.id}><div className="c6-plate-head"><span className="c6-number">{number(i)}</span><h3>{p.title}</h3></div><Picture image={p.image}/><figcaption><p>{p.caption}</p><small>{p.application}</small>{link(p.detail,p.title,p.caption)}</figcaption></figure>)}</div>;break;
 case "C10": {const c=model.content.cases[selected];artwork=<div className="c6-case"><div className="c6-case-choices" role="group" aria-label="Choose a capability case">{model.content.cases.map((c,i)=><button key={c.id} type="button" aria-pressed={i===selected} onClick={()=>setSelected(i)}>{number(i)} / {c.title}</button>)}</div><h3 aria-live="polite">{c.title}</h3><div className="c6-evidence-pair">{[c.before,c.after].map((p,i)=><figure key={i}><small>{p.label}</small><Picture image={p.image}/><figcaption>{p.note}</figcaption></figure>)}</div><div className="c6-case-explanation"><p>{c.capability}</p><small>{c.evidence}</small></div></div>;break;}
 case "C11": {const p=model.content.paths[selected];artwork=<div className="c6-path"><h3>{model.content.question}</h3><div className="c6-path-choices" role="group" aria-label="Choose your starting need">{model.content.paths.map((p,i)=><button type="button" key={p.id} aria-pressed={i===selected} aria-controls={`${uid}-recommendation`} onClick={()=>setSelected(i)}>{p.need}</button>)}</div><div id={`${uid}-recommendation`} className="c6-recommendation" aria-live="polite"><small>A possible starting point</small><h4>{p.recommendation}</h4><p>{p.reason}</p><p className="c6-alternative">{p.alternative}</p>{link(p.detail,p.recommendation,p.reason)}</div></div>;break;}
 case "C12": {const {offerings,criteria}=model.content;artwork=<div className="c6-scopes"><div className="c6-mobile-only c6-scope-selectors">{([["Baseline",baseline,setBaseline],["Compare with",candidate,setCandidate]] as const).map(([label,value,set])=><label key={label}>{label}<select value={value} onChange={e=>set(Number(e.target.value))}>{offerings.map((o,i)=><option key={o.id} value={i}>{o.title}</option>)}</select></label>)}</div><table className="c6-desktop-only"><caption>Compare the scope of each offering</caption><thead><tr><th scope="col">A shared question</th>{offerings.map(o=><th scope="col" key={o.id}>{o.title}<small>{o.bestFor}</small></th>)}</tr></thead><tbody>{criteria.map((c,i)=><tr key={c}><th scope="row">{c}</th>{offerings.map(o=><td key={o.id}>{o.values[i]}</td>)}</tr>)}<tr><th scope="row">Boundary</th>{offerings.map(o=><td key={o.id}>{o.boundary}</td>)}</tr><tr><th scope="row">Explore</th>{offerings.map(o=><td key={o.id}>{link(o.detail,o.title,o.bestFor)}</td>)}</tr></tbody></table><div className="c6-mobile-only"><p aria-live="polite">{baseline===candidate?`Both columns show ${offerings[baseline].title}`:`${offerings[baseline].title} compared with ${offerings[candidate].title}`}</p><dl className="c6-scope-pairs">{[["Best for",offerings[baseline].bestFor,offerings[candidate].bestFor],...criteria.map((c,i)=>[c,offerings[baseline].values[i],offerings[candidate].values[i]]),["Boundary",offerings[baseline].boundary,offerings[candidate].boundary]].map(([label,a,b])=><div key={label}><dt>{label}</dt><dd><span>{a}</span><span>{b}</span></dd></div>)}</dl><div className="c6-scope-links">{[baseline,candidate].map((i,j)=><div key={j}>{link(offerings[i].detail,offerings[i].title,offerings[i].bestFor)}</div>)}</div></div></div>;break;}
 }
 return <section className={`c6-study c6-${model.kind.toLowerCase()}`} aria-labelledby={heading} data-study={model.kind}>
   <header className="c6-heading"><p className="c6-kicker">{model.content.brand} <span>Services / Capabilities</span></p><h2 id={heading}>{model.content.title}</h2><p className="c6-introduction">{model.content.introduction}</p></header>
   {artwork}
   {detail&&<aside className="c6-local-detail" id={detail.id} aria-label="Service destination preview"><small>Lab destination preview · Service Detail pages are a future phase</small><h3 ref={detailHeading} tabIndex={-1}>{detail.title}</h3><p>{detail.body}</p><button type="button" onClick={()=>{setDetail(null);returnLink.current?.focus();}}>Return to offerings</button></aside>}
 </section>;
}
