"use client";
import { ContentTextField } from "./ContentFields";
import type { SectionInstance } from "../../composition/schemas";
import { parseSection } from "../../composition/schemas";
import { creatorImage, creatorImagePackages } from "../creator-image-packages";
import { InquiryFormAppearanceControls } from "./InquiryFormAppearanceControls";
export function ComponentPresentationControls({ section, onChange }: { section: SectionInstance; onChange: (section: SectionInstance) => void }) {
  const patch = (key: string, value: unknown) => onChange(parseSection({ ...section, [key]: value }));
  const select = (label: string, value: string, options: readonly string[], onSelect: (value: string) => void) => <label key={label}>{label}<select aria-label={label} value={value} onChange={event => onSelect(event.target.value)}>{options.map(option => <option key={option} value={option}>{option.replace(/-/g," ")}</option>)}</select></label>;
  const number = (label: string, value: number, min: number, max: number, onSelect: (value: number) => void) => <ContentTextField key={label} label={label} type="number" value={String(value)} onChange={text => { const next=Number(text); if(text!=="" && Number.isFinite(next) && next>=min && next<=max) onSelect(next); }}/>;
  if (section.component === "proof.social-reach") return <details open className="composition-content-group"><summary>Stats & social links</summary>
    {select("Stats layout",section.statsLayout ?? "auto",["auto","grid","inline","stacked"],value => patch("statsLayout",value))}{select("Stat background",section.statSurface ?? "inherit",["inherit","transparent","surface","framed"],value => patch("statSurface",value))}{select("Stat alignment",section.statAlignment ?? "inherit",["inherit","left","center","right"],value => patch("statAlignment",value))}
    <div className="composition-controls">{number("Stat columns",section.statsColumns ?? 3,1,4,value => patch("statsColumns",value))}{number("Stat value size",section.statSize ?? 64,20,120,value => patch("statSize",value))}{number("Stat gap",section.statGap ?? 24,0,100,value => patch("statGap",value))}{number("Stat padding",section.statPadding ?? 24,0,100,value => patch("statPadding",value))}{number("Social icon size",section.socialIconSize ?? 24,16,64,value => patch("socialIconSize",value))}{number("Social link gap",section.linkGap ?? 12,0,80,value => patch("linkGap",value))}</div>
    {select("Social links alignment",section.linksAlignment ?? "inherit",["inherit","left","center","right"],value => patch("linksAlignment",value))}{select("Social links shape",section.linkShape ?? "pill",["square","soft","rounded","pill"],value => patch("linkShape",value))}
  </details>;
  if (section.component === "contact.inquiry") return <><details open className="composition-content-group"><summary>Contact appearance</summary>{select("Contact alignment",section.alignment ?? "left",["left","center","right"],value => patch("alignment",value))}{select("Contact treatment",section.appearance ?? "minimal",["minimal","editorial","panel"],value => patch("appearance",value))}{select("Contact image placement",section.imagePlacement ?? "right",["none","left","right","background"],value => patch("imagePlacement",value))}{number("Background overlay percent",Math.round((section.imageOverlay ?? .65)*100),0,90,value => patch("imageOverlay",value/100))}<p>Add an image in Content, then adjust its crop in Images and videos.</p></details>{section.content.form && <InquiryFormAppearanceControls value={section.formAppearance} onChange={value => patch("formAppearance",value)}/>}</>;
  if (section.component !== "proof.moving-chorus") return null;
  const cards = section.cardSettings ?? {};
  const card = (key: string, value: unknown) => patch("cardSettings",{...cards,[key]:value});
  const order = cards.order ?? ["portrait","quote","name","role","company"];
  return <details open className="composition-content-group"><summary>Testimonial card design</summary>
    <label><input type="checkbox" checked={cards.equalHeight ?? false} onChange={event => card("equalHeight",event.target.checked)}/>Equal card heights</label><p>Match the tallest card automatically, including after content or viewport changes.</p>
    {select("Card background",cards.design ?? "transparent",["transparent","outline","solid","editorial"],value => card("design",value))}{select("Card shape",cards.shape ?? "square",["square","soft","rounded"],value => card("shape",value))}{select("Card hover",cards.hover ?? "none",["none","lift","enlarge"],value => card("hover",value))}
    <div className="composition-controls">{number("Card width",cards.width ?? 400,220,900,value => card("width",value))}{number("Card minimum height",cards.minHeight ?? 0,0,800,value => card("minHeight",value))}{number("Card padding",cards.padding ?? 24,0,100,value => card("padding",value))}{number("Card gap",cards.gap ?? 24,0,100,value => card("gap",value))}{number("Quote size",cards.quoteSize ?? 24,14,64,value => card("quoteSize",value))}{number("Portrait size",cards.portraitSize ?? 72,32,240,value => card("portraitSize",value))}</div>
    {select("Card horizontal alignment",cards.horizontal ?? section.alignment,["left","center","right"],value => card("horizontal",value))}{select("Card vertical alignment",cards.vertical ?? "start",["start","center","end","spread"],value => card("vertical",value))}{select("Portrait frame",cards.portraitFrame ?? "square",["square","soft","circle","portrait"],value => card("portraitFrame",value))}{select("Portrait alignment",cards.portraitAlignment ?? section.alignment,["left","center","right"],value => card("portraitAlignment",value))}
    <fieldset><legend>Card content order</legend>{order.map((piece,index) => <div key={piece} className="composition-order-row"><span>{piece}</span><button type="button" aria-label={`Move ${piece} earlier`} disabled={index===0} onClick={() => { const next=[...order]; [next[index-1],next[index]]=[next[index],next[index-1]];card("order",next); }}>↑</button><button type="button" aria-label={`Move ${piece} later`} disabled={index===order.length-1} onClick={() => { const next=[...order]; [next[index+1],next[index]]=[next[index],next[index+1]];card("order",next); }}>↓</button>{piece!=="quote"&&<button type="button" onClick={() => card("order",order.filter(value=>value!==piece))}>Hide</button>}</div>)}{["portrait","name","role","company"].filter(piece=>!order.includes(piece as typeof order[number])).map(piece=><button type="button" key={piece} onClick={()=>card("order",[...order,piece])}>Show {piece}</button>)}</fieldset>
  </details>;
}
export function TestimonialPortraitControls({ section, onChange }: { section: SectionInstance; onChange: (section: SectionInstance) => void }) {
  if (section.component !== "proof.moving-chorus") return null;
  return <details className="composition-content-group"><summary>Portraits</summary>{section.content.voices.map(voice => <label key={voice.id}><input type="checkbox" checked={!!voice.portrait} onChange={event => {
    const voices = section.content.voices.map(item => item.id === voice.id ? { ...item, portrait: event.target.checked ? creatorImage(creatorImagePackages[0], "pov") : undefined } : item);
    onChange(parseSection({ ...section, content: { ...section.content, voices } }));
  }}/>Include portrait for {voice.author.name}</label>)}<p>Replace added portraits in Images and videos. Choose Portrait or Avatar author treatment in Design to display them.</p></details>;
}
