"use client";
import { ContentTextField } from "./ContentFields";
import { buttonShapes, hoverEffects, entranceEffects, mediaHoverEffects, type PresentationSettings, type HeadingSettings, type MotionSettings } from "../../presentation/schema";
import { coreIconNames } from "../../icons/names";
const headingDefaults = { titleSize: 64, eyebrowSize: 12, descriptionSize: 18, bodySize: 16, titleLineHeight: 1.08, bodyLineHeight: 1.65, eyebrowGap: 16, descriptionGap: 20, titleWidth: 1000, descriptionWidth: 760 };
const motionDefaults = { entrance: "fade", exit: "none", duration: 650, delay: 0, easing: "smooth", distance: 32, blur: 10, scale: .94, stagger: 0, sequence: "heading-first", threshold: .08, replay: false, mediaHover: "none", ctaHover: "none" } as const;
export function PresentationControls({ value = {}, inherited = {}, onChange, scope = "section", motionOnly = false, navigation = false }: {
  value?: PresentationSettings; inherited?: PresentationSettings; onChange: (value: PresentationSettings | undefined) => void;
  scope?: "site" | "page" | "section"; motionOnly?: boolean; navigation?: boolean;
}) {
  const patch = <K extends keyof PresentationSettings>(key: K, update: PresentationSettings[K]) => onChange({ ...value, [key]: update });
  const choices = (label: string, selected: string, options: readonly string[], change: (next: string) => void) => <label key={label}>{label}<select aria-label={label} value={selected} onChange={event => change(event.target.value)}>{options.map(option => <option key={option} value={option}>{option === "inherit" ? "Inherit" : option.replace(/-/g," ")}</option>)}</select></label>;
  const number = (label: string, selected: number, min: number, max: number, _step: number, change: (next: number) => void) => <ContentTextField key={label} label={label} type="number" value={String(selected)} onChange={text => { const next=Number(text); if (text!=="" && Number.isFinite(next) && next>=min && next<=max) change(next); }}/>;
  if (motionOnly) {
    const settings = { ...motionDefaults, ...inherited.motion, ...value.motion };
    const set = (key: keyof MotionSettings, next: unknown) => patch("motion", { ...value.motion, [key]: next });
    return <section className="composition-presentation"><h2>{scope === "section" ? "Section motion" : `${scope === "site" ? "Site" : "Page"} motion defaults`}</h2>
      {scope === "section" ? choices("Motion inheritance",value.motionMode ?? "inherit",["inherit","override","none"], next => onChange({ ...value, motionMode: next as PresentationSettings["motionMode"], ...(next === "override" && !value.motion ? { motion: { ...settings } } : {}) })) : <label><input type="checkbox" checked={!!value.motion} onChange={event => patch("motion", event.target.checked ? { ...motionDefaults, ...inherited.motion } : undefined)}/>Enable transition defaults</label>}
      {(scope === "section" ? value.motionMode === "override" : !!value.motion) && <>
        {choices("Into view",settings.entrance,entranceEffects,next => set("entrance",next))}
        {choices("Out of view",settings.exit,entranceEffects,next => set("exit",next))}
        <div className="composition-controls">{number("Duration (ms)",settings.duration,100,3000,50,next => set("duration",next))}{number("Delay (ms)",settings.delay,0,3000,50,next => set("delay",next))}{number("Distance (px)",settings.distance,0,180,2,next => set("distance",next))}{number("Blur (px)",settings.blur,0,30,1,next => set("blur",next))}{number("Scale",settings.scale,.65,1.3,.01,next => set("scale",next))}{number("Stagger (ms)",settings.stagger,0,400,20,next => set("stagger",next))}{number("Trigger inset",settings.threshold,0,.75,.05,next => set("threshold",next))}</div>
        {choices("Easing",settings.easing,["smooth","snappy","linear","spring"],next => set("easing",next))}{choices("Sequence",settings.sequence,["together","heading-first","media-first","reverse"],next => set("sequence",next))}
        <label><input type="checkbox" checked={settings.replay} onChange={event => set("replay",event.target.checked)}/>Replay when returning into view</label>
        {choices("Media hover",settings.mediaHover,mediaHoverEffects,next => set("mediaHover",next))}{choices("CTA animation",settings.ctaHover,hoverEffects,next => set("ctaHover",next))}
      </>}
      {navigation && <p>Navigation stays in place; its button and media hover settings still apply.</p>}<p>System reduced motion keeps content static. Use Replay in the toolbar to inspect transitions.</p>
    </section>;
  }
  const heading = { ...headingDefaults, ...inherited.heading, ...value.heading };
  const setHeading = (key: keyof HeadingSettings, next: number) => patch("heading",{...value.heading,[key]:next});
  const headingEnabled = scope === "section" ? value.headingMode === "override" : !!value.heading;
  return <section className="composition-presentation">
    {!navigation && <details open><summary>Typography & heading spacing</summary>
      {scope === "section" ? choices("Heading inheritance",value.headingMode ?? "inherit",["inherit","override","original"],next => onChange({ ...value, headingMode: next as PresentationSettings["headingMode"], ...(next === "override" && !value.heading ? { heading: { ...heading } } : {}) })) : <label><input type="checkbox" checked={!!value.heading} onChange={event => patch("heading",event.target.checked ? { ...heading } : undefined)}/>Use uniform heading sizes and spacing</label>}
      {headingEnabled && <div className="composition-controls">{number("Title size",heading.titleSize,20,180,1,next => setHeading("titleSize",next))}{number("Eyebrow size",heading.eyebrowSize,9,36,1,next => setHeading("eyebrowSize",next))}{number("Description size",heading.descriptionSize,12,36,1,next => setHeading("descriptionSize",next))}{number("Body size",heading.bodySize,12,30,1,next => setHeading("bodySize",next))}{number("Title line height",heading.titleLineHeight,.85,1.8,.01,next => setHeading("titleLineHeight",next))}{number("Body line height",heading.bodyLineHeight,1.1,2.2,.05,next => setHeading("bodyLineHeight",next))}{number("Eyebrow gap",heading.eyebrowGap,0,100,1,next => setHeading("eyebrowGap",next))}{number("Description gap",heading.descriptionGap,0,100,1,next => setHeading("descriptionGap",next))}{number("Title width",heading.titleWidth,240,1600,20,next => setHeading("titleWidth",next))}{number("Description width",heading.descriptionWidth,240,1400,20,next => setHeading("descriptionWidth",next))}</div>}
    </details>}
    <details><summary>Button defaults</summary><p>Applies to buttons across this {scope}. Individual CTA choices take precedence.</p>
      {([['shape',buttonShapes],['hover',hoverEffects],['variant',["primary","secondary","outline","ghost","text","underline","inverse"]],['size',["small","medium","large","display"]],['iconPosition',["leading","trailing"]]] as const).map(([key,options]) => choices(`Button ${key}`,String(value.buttons?.[key] ?? "inherit"),["inherit",...options],next => patch("buttons",{...value.buttons,[key]:next === "inherit" ? undefined : next})))}
      {choices("Default button icon",value.buttons?.icon === null ? "none" : value.buttons?.icon ?? "inherit",["inherit","none",...coreIconNames],next => patch("buttons",{...value.buttons,icon:next === "inherit" ? undefined : next === "none" ? null : next as NonNullable<PresentationSettings["buttons"]>["icon"]}))}
    </details>
    <details><summary>Media & navigation controls</summary>{choices("Text control icon",value.controls?.icon === null ? "none" : value.controls?.icon ?? "inherit",["inherit","none",...coreIconNames],next => patch("controls",{...value.controls,icon:next === "inherit" ? undefined : next === "none" ? null : next as NonNullable<PresentationSettings["controls"]>["icon"]}))}{choices("Control icon position",value.controls?.iconPosition ?? "leading",["leading","trailing"],next => patch("controls",{...value.controls,iconPosition:next as "leading" | "trailing"}))}{choices("Control shape",value.controls?.shape ?? "inherit",["inherit",...buttonShapes],next => patch("controls",{...value.controls,shape:next === "inherit" ? undefined : next as NonNullable<PresentationSettings["controls"]>["shape"]}))}{choices("Control treatment",value.controls?.treatment ?? "inherit",["inherit","filled","outline","bare"],next => patch("controls",{...value.controls,treatment:next === "inherit" ? undefined : next as NonNullable<PresentationSettings["controls"]>["treatment"]}))}{choices("Control hover",value.controls?.hover ?? "inherit",["inherit",...hoverEffects],next => patch("controls",{...value.controls,hover:next === "inherit" ? undefined : next as NonNullable<PresentationSettings["controls"]>["hover"]}))}{number("Control size",value.controls?.size ?? inherited.controls?.size ?? 44,32,80,2,next => patch("controls",{...value.controls,size:next}))}{(['mediaIcon','previousIcon','nextIcon'] as const).map(key => choices(key === 'mediaIcon' ? 'Media action icon' : key === 'previousIcon' ? 'Previous control icon' : 'Next control icon',value.controls?.[key] ?? "inherit",["inherit",...coreIconNames],next => patch("controls",{...value.controls,[key]:next === "inherit" ? undefined : next})))}</details>
    {!navigation && <details><summary>Viewport & section spacing</summary>{choices("Section height",value.viewport?.height ?? "inherit",["inherit","natural","half","three-quarter","viewport","one-and-half","custom"],next => patch("viewport",{...value.viewport,height:next === "inherit" ? undefined : next as NonNullable<PresentationSettings["viewport"]>["height"]}))}{value.viewport?.height === "custom" && number("Minimum viewport percent",value.viewport.minimum ?? 100,25,250,5,next => patch("viewport",{...value.viewport,minimum:next}))}{number("Section vertical padding",value.viewport?.padding ?? inherited.viewport?.padding ?? 80,0,240,4,next => patch("viewport",{...value.viewport,padding:next}))}{choices("Vertical content alignment",value.viewport?.alignment ?? "center",["start","center","end"],next => patch("viewport",{...value.viewport,alignment:next as NonNullable<PresentationSettings["viewport"]>["alignment"]}))}</details>}
    <button type="button" onClick={() => onChange(undefined)}>Reset {scope} presentation overrides</button>
  </section>;
}
