"use client";
import { useRef, useState } from "react";
import { getSectionContract } from "../../composition/catalog";
import { pageTypes } from "../../registry/types";
import { type SiteDefinition, type SitePage, type SlotName } from "../../site/model";
import { addPage, deletePage, deletionImpact, duplicatePage, movePage, updatePage } from "../../site/operations";
import { descendantIds, resolveRoutes, siblings } from "../../site/routes";
import { deserializeSite, serializeSite } from "../../site/persistence";
import { makeComplexSiteFixture } from "./site-fixture";
export function SiteTree({ site, pageId, onChange, onSelect, onImport }: { site: SiteDefinition; pageId: string; onChange: (site: SiteDefinition) => void; onSelect: (id: string) => void; onImport?: (site: SiteDefinition) => void }) {
  const [error, setError] = useState("");
  const [strategy, setStrategy] = useState<"subtree" | "reparent">("reparent");
  const [json, setJson] = useState("");
  const [exportDraft, setExportName] = useState({value:site.title,base:site.title});
  const exportName=exportDraft.base===site.title?exportDraft.value:site.title;
  const dialog = useRef<HTMLDialogElement>(null), importDialog = useRef<HTMLDialogElement>(null), fileInput = useRef<HTMLInputElement>(null);
  const current = site.pages.find(page => page.id === pageId)!, routes = resolveRoutes(site), impact = deletionImpact(site, pageId, strategy);
  function attempt(operation: () => void) { try { operation(); setError(""); } catch (error) { setError(error instanceof Error ? error.message : "Invalid page operation."); } }
  function branch(parentId: string | null) { const pages = siblings(site, parentId); return <ol className="composition-site-tree">{pages.map((page, index) => <li key={page.id}>
    <div><button type="button" className="composition-page-choice" aria-current={page.id === pageId ? "page" : undefined} onClick={() => onSelect(page.id)}>{page.navLabel ?? page.title}<span>{page.pageType} · {page.showInNavigation ? "In Navigation" : "Hidden"}<small>{routes.get(page.id)}</small></span></button>
    <button type="button" aria-label={`Move ${page.title} up`} disabled={index === 0} onClick={() => attempt(() => onChange(movePage(site, page.id, -1)))}>↑</button><button type="button" aria-label={`Move ${page.title} down`} disabled={index === pages.length - 1} onClick={() => attempt(() => onChange(movePage(site, page.id, 1)))}>↓</button></div>{site.pages.some(child => child.parentId === page.id) ? branch(page.id) : null}
  </li>)}</ol>; }
  function makePage(duplicate = false) { attempt(() => { const result = duplicate ? duplicatePage(site, pageId) : addPage(site); onChange(result.site); onSelect(result.pageId); }); }
  function download() { attempt(() => {
    const title = exportName.trim();
    if (!title || title.length > 180) throw new Error("Give this variant a name between 1 and 180 characters.");
    const filename = title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0,100) || "site-variant";
    const url = URL.createObjectURL(new Blob([serializeSite({ ...site, title })], { type: "application/json" })), anchor = document.createElement("a");
    anchor.href = url; anchor.download = `${filename}.site.json`; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
  }); }
  return <section className="composition-panel"><h2>Site Tree</h2><p>{site.title} · {site.pages.length} pages</p><div className="composition-page-tools"><button type="button" onClick={() => makePage()}>Add page</button><button type="button" onClick={() => makePage(true)}>Duplicate page</button><button type="button" onClick={() => dialog.current?.showModal()}>Delete page</button></div>
    {branch(null)}<PageDetails key={`${pageId}-${JSON.stringify({ ...current, sections: undefined })}`} site={site} page={current} onApply={patch => attempt(() => onChange(updatePage(site, pageId, patch)))}/>
    <details><summary>Portable site document</summary><label className="composition-control">Variant name<input aria-label="Variant name" value={exportName} maxLength={180} onChange={event => setExportName({value:event.target.value,base:site.title})} placeholder="Creator variant 01" /></label><p>Export each design as a separate named JSON file. Local draft stores one working site in this browser; exported files retain all pages, sections, creative layers and actions.</p><div className="composition-page-tools"><button type="button" onClick={download}>Export site JSON</button><button type="button" onClick={() => fileInput.current?.click()}>Import site file</button><input ref={fileInput} type="file" accept=".json,application/json" hidden aria-label="Import site file" onChange={async event => { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; try { setJson(serializeSite(deserializeSite(await file.text()))); setError(""); importDialog.current?.showModal(); } catch (failure) { setError(failure instanceof Error ? failure.message : "Invalid site file."); } }}/><button type="button" onClick={() => { setJson(serializeSite(site)); importDialog.current?.showModal(); }}>Import / inspect JSON</button><button type="button" onClick={() => { setJson(serializeSite(makeComplexSiteFixture())); importDialog.current?.showModal(); }}>Load complex QA fixture</button></div><p>Import replaces this local site after confirmation. Export your draft first if needed.</p></details><p role="alert">{error}</p>
    <dialog ref={dialog} className="composition-clear-dialog" aria-labelledby="delete-page-title"><h2 id="delete-page-title">Delete {current.title}?</h2><p>{impact.children} descendant page(s). {impact.incoming.length} incoming action(s) will need repair.</p><label>Child-page strategy<select aria-label="Child-page strategy" value={strategy} onChange={event => setStrategy(event.target.value as typeof strategy)}><option value="reparent">Reparent children to this page’s parent</option><option value="subtree">Delete the entire subtree</option></select></label><p>{impact.removed.size} page(s) will be removed. Incoming actions remain visible warnings.</p>{impact.incoming.length > 0 && <ul>{impact.incoming.map((value, index) => <li key={index}>{value}</li>)}</ul>}<div><button type="button" autoFocus onClick={() => dialog.current?.close()}>Cancel</button><button type="button" disabled={impact.removed.has(site.navigation.homePageId)} onClick={() => attempt(() => { const next = deletePage(site, pageId, strategy); onChange(next); onSelect(next.pages.find(page => page.id === current.parentId)?.id ?? next.navigation.homePageId); dialog.current?.close(); })}>Confirm delete page</button></div>{impact.removed.has(site.navigation.homePageId) && <p>Choose another site home page in Site before deletion.</p>}</dialog>
    <dialog ref={importDialog} className="composition-clear-dialog composition-site-import" aria-labelledby="import-site-title"><h2 id="import-site-title">Replace site from JSON</h2><label>Site JSON<textarea aria-label="Site JSON" rows={16} value={json} onChange={event => setJson(event.target.value)} spellCheck={false}/></label><p role="alert">{error}</p><div><button type="button" autoFocus onClick={() => importDialog.current?.close()}>Cancel</button><button type="button" onClick={() => attempt(() => { const next = deserializeSite(json); (onImport ?? onChange)(next); setExportName({value:next.title,base:next.title}); onSelect(next.navigation.homePageId); importDialog.current?.close(); })}>Confirm replace site</button></div></dialog>
  </section>;
}
function PageDetails({ site, page, onApply }: { site: SiteDefinition; page: SitePage; onApply: (patch: Partial<Omit<SitePage, "id">>) => void }) {
  const [draft, setDraft] = useState(structuredClone(page));
  const descendants = descendantIds(site, page.id);
  const field = (label: string, value: string, change: (value: string) => void) => <label className="composition-control">{label}<input aria-label={label} value={value} onChange={event => change(event.target.value)}/></label>;
  return <form className="composition-page-details" onSubmit={event => { event.preventDefault(); onApply({ title: draft.title, navLabel: draft.navLabel, slug: draft.slug, routeOverride: draft.routeOverride, pageType: draft.pageType, parentId: draft.parentId, order: draft.order, showInNavigation: draft.showInNavigation, status: draft.status, seo: draft.seo, slots: draft.slots, previousRoutes: draft.previousRoutes }); }}><h3>Page details</h3><p>Stable ID: {page.id}</p>
    {field("Page title", draft.title, title => setDraft(value => ({ ...value, title })))}
    {field("Navigation label", draft.navLabel ?? "", navLabel => setDraft(value => ({ ...value, navLabel: navLabel || undefined })))}
    {field("Page slug", draft.slug, slug => setDraft(value => ({ ...value, slug })))}
    <label className="composition-control">Page type<select aria-label="Page type" value={draft.pageType} onChange={event => setDraft(value => ({ ...value, pageType: event.target.value as SitePage["pageType"] }))}>{pageTypes.map(type => <option key={type}>{type}</option>)}</select></label>
    <label className="composition-control">Parent page<select aria-label="Parent page" value={draft.parentId ?? ""} onChange={event => setDraft(value => ({ ...value, parentId: event.target.value || null }))}><option value="">Top level</option>{site.pages.filter(candidate => candidate.id !== page.id && !descendants.has(candidate.id)).map(candidate => <option key={candidate.id} value={candidate.id}>{resolveRoutes(site).get(candidate.id)} · {candidate.title}</option>)}</select></label>
    <label className="composition-control">Page status<select aria-label="Page status" value={draft.status} onChange={event => setDraft(value => ({ ...value, status: event.target.value as SitePage["status"] }))}><option>draft</option><option>published</option></select></label>
    <label><input type="checkbox" checked={draft.showInNavigation} onChange={event => setDraft(value => ({ ...value, showInNavigation: event.target.checked }))}/> Show in Navigation</label>
    {(["navigation", "footer"] as const).map(name => <label className="composition-control" key={name}>{name === "navigation" ? "Page Navigation" : "Page Footer"}<select aria-label={name === "navigation" ? "Page Navigation" : "Page Footer"} value={draft.slots[name].mode} onChange={event => { const mode = event.target.value as "inherit" | "omit" | "replace"; const section = site.globals[name]; setDraft(value => ({ ...value, slots: { ...value.slots, [name]: mode === "replace" && section ? { mode, section: structuredClone(section) } : { mode } } })); }}><option value="inherit">Inherit global {name}</option><option value="omit">Omit on this page</option>{draft.slots[name].mode === "replace" && <option value="replace">Explicit page replacement</option>}</select></label>)}
    <details><summary>SEO and route options</summary>{field("SEO title", draft.seo.title ?? "", title => setDraft(value => ({ ...value, seo: { ...value.seo, title: title || undefined } })))}{field("SEO description", draft.seo.description ?? "", description => setDraft(value => ({ ...value, seo: { ...value.seo, description: description || undefined } })))}<label><input type="checkbox" checked={draft.seo.noIndex ?? false} onChange={event => setDraft(value => ({ ...value, seo: { ...value.seo, noIndex: event.target.checked } }))}/> No index</label>{field("Explicit absolute route", draft.routeOverride ?? "", routeOverride => setDraft(value => ({ ...value, routeOverride })))}<p>Recorded previous routes: {page.previousRoutes.join(", ") || "None"}</p></details><button type="submit">Apply page details</button>
  </form>;
}
export function SiteStructureControls({ site, pageId, onChange }: { site: SiteDefinition; pageId: string; onChange: (site: SiteDefinition) => void }) {
  const [error, setError] = useState("");
  const page = site.pages.find(page => page.id === pageId)!;
  function share(name: SlotName) {
    const slot = page.slots[name]; if (slot.mode !== "replace") return;
    onChange({ ...site, globals: { ...site.globals, [name]: structuredClone(slot.section) }, pages: site.pages.map(candidate => candidate.id === pageId ? { ...candidate, slots: { ...candidate.slots, [name]: { mode: "inherit" } } } : candidate) });
  }
  return <section className="composition-panel"><h2>Site structure</h2><label className="composition-control">Site home page<select aria-label="Site home page" value={site.navigation.homePageId} onChange={event => onChange({ ...site, navigation: { ...site.navigation, homePageId: event.target.value } })}>{site.pages.map(page => <option key={page.id} value={page.id}>{page.title}</option>)}</select></label><label><input type="checkbox" checked={site.navigation.includeDrafts} onChange={event => onChange({ ...site, navigation: { ...site.navigation, includeDrafts: event.target.checked } })}/> Include draft pages in Navigation</label>
    {(["navigation", "footer"] as const).map(name => <div key={name}><p>Global {name}: {site.globals[name] ? getSectionContract(site.globals[name].component).structuralDNA : "Not configured"}. Current page: {page.slots[name].mode}.</p><button type="button" disabled={page.slots[name].mode !== "replace"} onClick={() => { try { share(name); setError(""); } catch (error) { setError(String(error)); } }}>Use page {name} globally</button><button type="button" disabled={page.slots[name].mode !== "inherit" || !site.globals[name]} onClick={() => onChange(updatePage(site, pageId, { slots: { ...page.slots, [name]: { mode: "replace", section: structuredClone(site.globals[name]!) } } }))}>Create page {name} override</button></div>)}<p>Production Footers support shared site-wide inheritance and explicit page overrides.</p><p role="alert">{error}</p>
  </section>;
}
