// Lab-only catalog. Client applications import ONLY their selected font loaders.
import localFont from "next/font/local";

const fraunces = localFont({ src: [{path: "./fonts/fraunces/fraunces-latin-full-normal.woff2", weight: "100 900", style: "normal"}, {path: "./fonts/fraunces/fraunces-latin-full-italic.woff2", weight: "100 900", style: "italic"}], variable: "--de-face-fraunces", display: "swap", preload: false, fallback: ["Georgia"], adjustFontFallback: "Times New Roman" });
const bodoni = localFont({ src: [{path: "./fonts/bodoni-moda/bodoni-moda-latin-standard-normal.woff2", weight: "400 900", style: "normal"}, {path: "./fonts/bodoni-moda/bodoni-moda-latin-standard-italic.woff2", weight: "400 900", style: "italic"}], variable: "--de-face-bodoni", display: "swap", preload: false, fallback: ["Georgia"], adjustFontFallback: "Times New Roman" });
const publicSans = localFont({ src: [{path: "./fonts/public-sans/public-sans-latin-wght-normal.woff2", weight: "100 900", style: "normal"}], variable: "--de-face-public", display: "swap", preload: false, fallback: ["Arial"], adjustFontFallback: "Arial" });
const jost = localFont({ src: [{path: "./fonts/jost/jost-latin-wght-normal.woff2", weight: "100 900", style: "normal"}], variable: "--de-face-jost", display: "swap", preload: false, fallback: ["Arial"], adjustFontFallback: "Arial" });
const anton = localFont({ src: [{path: "./fonts/anton/anton-latin-400-normal.woff2", weight: "400", style: "normal"}], variable: "--de-face-anton", display: "swap", preload: false, fallback: ["Arial"], adjustFontFallback: "Arial" });
const source = localFont({ src: [{path: "./fonts/source-sans-3/source-sans-3-latin-wght-normal.woff2", weight: "200 900", style: "normal"}], variable: "--de-face-source", display: "swap", preload: false, fallback: ["Arial"], adjustFontFallback: "Arial" });
const plex = localFont({ src: [{path: "./fonts/ibm-plex-mono/ibm-plex-mono-latin-400-normal.woff2", weight: "400", style: "normal"}, {path: "./fonts/ibm-plex-mono/ibm-plex-mono-latin-500-normal.woff2", weight: "500", style: "normal"}], variable: "--de-face-plex", display: "swap", preload: false, fallback: ["Courier New", "monospace"], adjustFontFallback: false });
const archivo = localFont({ src: [{path: "./fonts/archivo-black/archivo-black-latin-400-normal.woff2", weight: "400", style: "normal"}], variable: "--de-face-archivo", display: "swap", preload: false, fallback: ["Arial"], adjustFontFallback: "Arial" });
const recursive = localFont({ src: [{path: "./fonts/recursive/recursive-latin-full-normal.woff2", weight: "300 1000", style: "normal"}], variable: "--de-face-recursive", display: "swap", preload: false, fallback: ["Arial"], adjustFontFallback: "Arial" });
const cormorant = localFont({ src: [{path: "./fonts/cormorant-garamond/cormorant-garamond-latin-wght-normal.woff2", weight: "300 700", style: "normal"}, {path: "./fonts/cormorant-garamond/cormorant-garamond-latin-wght-italic.woff2", weight: "300 700", style: "italic"}], variable: "--de-face-cormorant", display: "swap", preload: false, fallback: ["Georgia"], adjustFontFallback: "Times New Roman" });
export const labFontClasses = [fraunces.variable, bodoni.variable, publicSans.variable, jost.variable, anton.variable, source.variable, plex.variable, archivo.variable, recursive.variable, cormorant.variable].join(" ");
