"use client";
import { useState, type ReactNode } from "react";
import { collection003BReview } from "../../registry/creative-review";
import { LabEditor } from "../editor/LabEditor";
import { NavigationStudyPreview } from "./Study";
import { navigationStudies } from "./studies";
import { navigationContexts, adaptationHeroes, type BrandTreatment } from "./fixtures";
import { configurationIssues, navigationChoiceLabel, defaultConfig, heroOptions, navigationControls, updateNavigationConfig, type HeroContext, type NavigationConfig } from "./contracts";

export function NavigationCollectionGallery({toolbar,workspaceSwitch}:{toolbar?:ReactNode;workspaceSwitch?:ReactNode}) {
 const [selected,setSelected]=useState("NX01"),[adaptation,setAdaptation]=useState(0),[width,setWidth]=useState(1440),[tab,setTab]=useState("study"),[overview,setOverview]=useState(false),[hero,setHero]=useState<HeroContext>("hero.front-page"),[config,setConfig]=useState(defaultConfig(navigationStudies[0])),[logo,setLogo]=useState<BrandTreatment|"authored">("authored"),[stress,setStress]=useState("authored");
 const [heroAlignment,setHeroAlignment]=useState<"left"|"center"|"right">("left");
 const study=navigationStudies.find(s=>s.id===selected)!;
 function selectStudy(id:string){const next=navigationStudies.find(s=>s.id===id)!;setSelected(id);const defaults=defaultConfig(next);setConfig(defaults);if(configurationIssues(next,defaults,hero).length)setHero("hero.comparison");}
 const preview=(s=study)=>{const cfg=s.id===study.id?config:defaultConfig(s),h=configurationIssues(s,cfg,hero).length?"hero.comparison":hero;return <NavigationStudyPreview study={s} adaptation={adaptation} config={cfg} hero={h} heroAlignment={heroAlignment} logo={logo==="authored"?undefined:logo} long={stress==="long"} missingLogo={stress==="missing"}/>;};
 const notes=[
  ["Structural DNA",study.dna],["IA scale",`${study.scale} · ${study.destinations.join("–")} destinations · ${study.nested?"parent + child hierarchy":"flat IA"}`],
  ["Desktop",study.desktop],["Mobile",study.mobile],["Expansion",study.expansion],
  ["Alignment",Object.entries(study.supportedAlignments).map(([key,v])=>`${key}: ${v.join(" / ")}`).join("; ")],
  ["Hero / background",`${study.positions.join(" / ")}; ${study.backgrounds.join(" / ")}; ${study.contrasts.join(" / ")}. Eight existing Heroes and two full-image proposals are available. Hero-centric mode stays transparent until the measured Hero leaves view; select text contrast for the opening. Dropdowns always overlay page content.`],
  ["Utilities",study.utilities.join(" / ")],["Scroll behavior",study.scroll.join(" / ")],["Motion",study.motion],["Compatibility limits",study.constraints],
 ];
 return <LabEditor title="Design Lab" toolbar={toolbar} workspaceSwitch={workspaceSwitch} canvasWidth={overview?1440:width} resetKey={`${selected}-${adaptation}-${width}-${overview}`} activeTab={tab} onTabChange={setTab} tabs={[
  {id:"study",label:"Study",content:<div className="n3-notes"><h2>Collection 003B · Navigation Expansion</h2><p>Creative Study · 12 approved references · 36 brand adaptations. Production Systems are available in the component catalog and Composition. Desktop behavior refinements are ready; mobile art-direction refinement is deferred. Open Menu / Index / Directory inside the artboard to inspect the expanded state.</p><div className="n3-controls">
   <label>Navigation study<select aria-label="Navigation study" value={selected} onChange={e=>selectStudy(e.target.value)}>{navigationStudies.map(s=><option key={s.id} value={s.id}>{s.id} · {s.name}</option>)}</select></label>
   <label>Client adaptation<select aria-label="Navigation adaptation" value={adaptation} onChange={e=>{const i=Number(e.target.value);setAdaptation(i);const next=adaptationHeroes[i];setHero(configurationIssues(study,config,next).length?"hero.comparison":next);}}>{navigationContexts.map((c,i)=><option key={c.id} value={i}>{c.brand} · {c.kind}</option>)}</select></label>
   <label>Client artboard<select aria-label="Navigation artboard" value={width} onChange={e=>setWidth(Number(e.target.value))}>{[1440,1024,768,390,320].map(w=><option key={w} value={w}>{w}px · {w>1000?"Desktop":w>600?"Tablet":"Mobile"}</option>)}</select></label>
   <label>Hero context<select aria-label="Navigation Hero" value={hero} onChange={e=>setHero(e.target.value as HeroContext)}>{heroOptions.filter(h=>!configurationIssues(study,config,h).length).map(h=><option key={h} value={h}>{h.replace("hero.","")}{h==="hero.full-scene"||h==="hero.scene-poster"?" · proposal":""}</option>)}</select></label>
   {["hero.comparison","hero.full-scene","hero.scene-poster"].includes(hero)&&<label>Hero content placement<select aria-label="Navigation Hero alignment" value={heroAlignment} onChange={e=>setHeroAlignment(e.target.value as typeof heroAlignment)}>{["left","center","right"].map(v=><option key={v}>{v}</option>)}</select></label>}
   <label>Brand treatment<select aria-label="Brand treatment" value={logo} onChange={e=>setLogo(e.target.value as BrandTreatment|"authored")}>{["authored","wordmark","symbol","combined","image","text"].map(l=><option key={l}>{l}</option>)}</select></label>
   <label>Content resilience<select aria-label="Navigation resilience" value={stress} onChange={e=>setStress(e.target.value)}><option value="authored">Authored fixtures</option><option value="long">Long destination labels</option><option value="missing">Missing image logo → text</option></select></label>
   {Object.entries(navigationControls(study)).map(([key,values])=>{const choices=values.filter(value=>!configurationIssues(study,updateNavigationConfig(config,{[key]:value}),hero).length);return choices.length>1?<label key={key}>{({dockStyle:"Dock style",dockAlignment:"Dock placement",dockWidth:"Dock width",dockOffset:"Edge spacing",priorityLinks:"Visible priority links"} as Record<string,string>)[key]??key} {key==="brand"||key==="primary"||key==="actions"?"alignment":""}<select aria-label={`Navigation ${key}`} value={String(config[key as keyof NavigationConfig])} onChange={e=>setConfig(updateNavigationConfig(config,{[key]:e.target.value}))}>{choices.map(v=><option key={v} value={v}>{navigationChoiceLabel(key,v)}</option>)}</select></label>:null;})}
   {config.scroll==="solidify"&&<label>Hero text contrast<select aria-label="Navigation Hero contrast" value={config.heroContrast} onChange={e=>setConfig({...config,heroContrast:e.target.value as NavigationConfig["heroContrast"]})}><option value="brand">Brand foreground</option><option value="light-on-dark">Light text on dark Hero</option><option value="dark-on-light">Dark text on light Hero</option></select></label>}
   {study.utilities.some(u=>u!=="cta")&&<label>Utility visibility<select aria-label="Navigation utilities" value={config.utilities?"visible":"hidden"} onChange={e=>setConfig({...config,utilities:e.target.value==="visible"})}><option value="visible">Visible presentation slots</option><option value="hidden">No utility slots</option></select></label>}
   {study.utilities.includes("cta")&&<label>CTA visibility<select aria-label="Navigation CTA" value={config.cta?"visible":"hidden"} onChange={e=>setConfig({...config,cta:e.target.value==="visible"})}><option value="visible">Visible</option><option value="hidden">Hidden</option></select></label>}
   <button type="button" aria-pressed={overview} onClick={()=>setOverview(!overview)}>{overview?"Return to selected study":"Compare twelve studies"}</button>
  </div><h3>{study.name}</h3><p>{study.dna}</p><p>{study.typography[adaptation]} typography · {study.art[adaptation]} art direction.</p><p>All studies offer sticky, reveal and Hero-centric motion. Hero-centric mode overlays the Hero with no background; it solidifies at the actual Hero boundary. NX04 stays floating in every mode. Choose the Hero text contrast to match its image. Scroll inside the artboard to inspect.</p></div>},
  {id:"contract",label:"Contract",content:<div className="n3-notes"><h2>{study.id} · {study.name}</h2><dl>{notes.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><h3>Composition contract proposal</h3><p>This same typed capability contract is ready for a future Composition inspector. All studies have human creative approval. Production migration remains a separate phase.</p><pre>{JSON.stringify(study,null,2)}</pre></div>},
  {id:"review",label:"Review",content:<div className="n3-notes"><h2>Human creative review</h2><p>All twelve concepts are approved. Preserve their individual flexibility. Every study now supports sticky, reveal and Hero-centric behavior. Dropdowns overlay the page; mobile refinement is intentionally secondary.</p><h3>{study.id} · {collection003BReview[study.id].status}</h3><p>{collection003BReview[study.id].note}</p><h3>NX04 · priority floating family</h3><p>Capsule, architectural frame, soft glass and segmented treatments; left/center/right docking, compact/wide widths, close/relaxed offsets, optional priority links, CTA and utility visibility. All ten Hero contexts and all five scroll modes remain available without introducing a header spacer.</p><h3>Three unrelated adaptations</h3><p>COMMON / GROUND: warm stone, architectural wordmark, practice/place hierarchy and project inquiry. OFF HOURS: acid yellow, broad image logo, collection hierarchy and drop CTA. SECTOR ZERO: cool technical palette, symbol + wordmark, deep platform/resources taxonomy and walkthrough CTA. Ten Hero contexts are independently swappable.</p><h3>Closest pairs</h3><p>Datum / Meridian: single baseline versus fixed central hinge and separated utilities. Pocket / Viewfinder: compact nonmodal fan versus media-aware corner frame and side modal. Dispatch / Folio: visible destination register versus full viewport index. Atlas / Channel: simultaneous taxonomy versus selected department and staged mobile drilldown. Margin / Threshold: reserved side column versus after-Hero route shelf. Open Doors: graphic priority board without nested IA.</p><p>All twelve are approved, including the floating and fullscreen families. NX04 is explicitly important to the library. The original shortlist is historical and does not limit this approval.</p><h3>Engine limits</h3><p>The original creative studies remain here for reference. The production systems now expose typed brand assets, semantic nested destinations, per-slot alignment, utility slots and scroll policies. Composition measures safe zones, reserves Margin Rail’s column and places Threshold’s shelf after the Hero. Route providers and future Motion expansion remain separate.</p></div>},
 ]}>{overview?<div className="n3-overview">{navigationStudies.map(s=><article key={s.id}><h3>{s.id} / {s.name} · {s.scale}</h3><div inert>{preview(s)}</div><button onClick={()=>{selectStudy(s.id);setOverview(false);}}>Inspect {s.name}</button></article>)}</div>:preview()}</LabEditor>;
}
