"use client";

import Image from "next/image";
import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowUpRight, Check } from "lucide-react";
import {
  EXPRESS_CHECKOUT_URL,
  EXPRESS_PRICE,
  EXPRESS_TEMPLATES,
} from "@/lib/constants";
/*
  Generated by vigil-leadgen/scripts/previews.sh. The hard-coded hex per card in
  `constants.ts` had drifted from every template it labelled — the salon card
  was still showing a plum on a page that is now stone and bronze.
*/
import accentsBySlug from "@/lib/express-accents.json";

import {
  GradientEdge,
  SpotlightOverlay,
  handleSpotlightMove,
} from "@/components/ui/Spotlight";

const ACCENTS = accentsBySlug as Record<string, string>;

const included = [
  "Single-page website",
  "Built on your industry's template",
  "Your logo, colours and photos",
  "Mobile responsive",
  "Basic SEO",
  "One round of revisions",
  "Live in 1-2 business days",
];

const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: { staggerChildren: 0.08, delayChildren: 0.1 },
  },
};

const itemVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.5, ease: "easeOut" } },
};

/**
 * Stripe Payment Links accept `client_reference_id` as a query parameter and
 * hand it back on the `checkout.session.completed` webhook, which is how an
 * order knows which template was bought.
 *
 * The separator is chosen rather than hardcoded: today's link carries no query
 * string, but a link copied from Stripe with one (a prefilled price, a locale)
 * would otherwise produce two `?` and silently drop the reference.
 */
function checkoutUrl(slug: string) {
  const separator = EXPRESS_CHECKOUT_URL.includes("?") ? "&" : "?";
  return `${EXPRESS_CHECKOUT_URL}${separator}client_reference_id=${encodeURIComponent(slug)}`;
}

function TemplateCard({
  template,
  canCheckout,
}: {
  template: (typeof EXPRESS_TEMPLATES)[number];
  canCheckout: boolean;
}) {
  const accent = ACCENTS[template.slug] ?? template.accent;
  const href = `/express-templates/${template.slug}.html`;

  return (
    <motion.article
      variants={itemVariants}
      whileHover={{ y: -6 }}
      onMouseMove={handleSpotlightMove}
      /*
        `!p-0` because the preview bleeds to the card's edges, so the padding
        lives on the content below it instead. Not done with negative margins:
        `.glass` carries a global padding that drops to 16px under 430px and
        12px under 375px, so any hardcoded negative margin is wrong there.
      */
      className="group/spot glass relative flex flex-col overflow-hidden rounded-2xl border border-[color:var(--border)] !p-0"
    >
      <SpotlightOverlay />
      <GradientEdge strength={30} />

      {/*
        Hovering the *image* scrolls it to reveal the rest of the page — scoped
        to `group/preview`, not the card, or it also fires from the title and
        the buttons and the picture moves with the cursor nowhere near it.

        900x1500 in a 4:3 window, so the travel is (1500 - 675) / 1500 = 55%.
        Uniform capture dimensions are what make that one number for all six.
      */}
      <div className="group/preview relative">
        <a
          href={href}
          target="_blank"
          rel="noopener noreferrer"
          className="relative block aspect-[4/3] overflow-hidden rounded-t-[inherit] border-b border-[color:var(--border)] bg-[color:var(--bg-secondary)]"
        >
          <Image
            src={`/express-templates/previews/${template.slug}.jpg`}
            alt={`The ${template.industry} template, shown as an example site for ${template.example}`}
            width={900}
            height={1500}
            loading="lazy"
            sizes="(max-width: 768px) 100vw, (max-width: 1024px) 50vw, 33vw"
            className="w-full h-auto transition-transform duration-[2800ms] ease-linear group-hover/preview:-translate-y-[55%]"
          />
          <span className="pointer-events-none absolute bottom-2 right-2 rounded-full bg-black/55 px-2.5 py-1 text-[11px] font-medium text-white opacity-0 backdrop-blur-sm transition-opacity duration-300 group-hover/preview:opacity-100 [@media(hover:none)]:opacity-100">
            Open full template
          </span>
        </a>
      </div>

      <div className="flex flex-1 flex-col p-5 sm:p-6 md:p-7">
        {/* The template's real accent, generated rather than stored here. */}
        <span
          aria-hidden="true"
          className="mb-4 block h-1 w-28 rounded-full"
          style={{ backgroundColor: accent }}
        />

        <h2 className="text-xl font-bold text-[color:var(--text-primary)] mb-1">
          {template.industry}
        </h2>

        <p className="text-xs uppercase tracking-[0.14em] text-[color:var(--text-secondary)] mb-4">
          Example: {template.example}
        </p>

        <p className="text-sm text-[color:var(--text-secondary)] flex-grow mb-6">
          {template.description}
        </p>

        {/*
          Side by side, each an equal half. The labels are short because of it:
          at three columns a card is 304px, leaving 246px for the pair, and the
          buttons' own `px-6` spends 96px of that before any text is drawn.
          `min-w-0` is what lets them shrink to half — without it the intrinsic
          text width is a floor and the row overflows the card.
        */}
        <div className="flex gap-3">
          <a
            href={href}
            target="_blank"
            rel="noopener noreferrer"
            className="btn-secondary flex-1 basis-0 min-w-0 !px-3 text-center inline-flex items-center justify-center gap-1.5"
          >
            View
            <ArrowUpRight size={16} className="flex-shrink-0" />
          </a>
          <a
            href={canCheckout ? checkoutUrl(template.slug) : "/#contact"}
            className="btn-primary flex-1 basis-0 min-w-0 !px-3 text-center"
          >
            {canCheckout ? `Buy \u00b7 $${EXPRESS_PRICE}` : "Enquire"}
          </a>
        </div>
      </div>
    </motion.article>
  );
}

export function ExpressCatalogue() {
  // Until the Stripe link exists, "Buy now" would be a button that goes
  // nowhere. Falling back to the contact form keeps the page honest rather
  // than shipping a dead primary action.
  const canCheckout = EXPRESS_CHECKOUT_URL.length > 0;

  return (
    <section className="section-padding relative overflow-hidden">
      <div className="container-wide">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="max-w-2xl mx-auto text-center mb-16"
        >
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-[color:var(--accent)]/10 border border-[color:var(--accent)]/30 mb-6">
            <div className="w-2 h-2 rounded-full bg-[color:var(--accent)]" />
            <span className="text-sm font-medium text-[color:var(--accent)]">
              Express Sites &middot; ${EXPRESS_PRICE}
            </span>
          </div>

          <h1 className="text-4xl md:text-5xl font-bold text-[color:var(--text-primary)] mb-4">
            Pick your industry. Launch this week.
          </h1>

          <p className="text-lg text-[color:var(--text-secondary)]">
            Every Express site is built from one of the templates below, then
            filled with your own content, colours and photos. Look at the full
            example before you decide &mdash; what you see is what you get.
          </p>
        </motion.div>

        {/* What's included */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.15 }}
          className="glass rounded-2xl p-6 md:p-8 mb-14 max-w-4xl mx-auto"
        >
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-x-8 gap-y-3">
            {included.map((item) => (
              <div
                key={item}
                className="flex items-center gap-3 text-[color:var(--text-secondary)]"
              >
                <Check
                  size={16}
                  className="text-[color:var(--accent)] flex-shrink-0"
                />
                <span className="text-sm">{item}</span>
              </div>
            ))}
          </div>
        </motion.div>

        {/* The templates */}
        <motion.div
          variants={containerVariants}
          initial="hidden"
          animate="visible"
          className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6"
        >
          {EXPRESS_TEMPLATES.map((template) => (
            <TemplateCard
              key={template.slug}
              template={template}
              canCheckout={canCheckout}
            />
          ))}
        </motion.div>

        {/* Footnote */}
        <motion.p
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.6, delay: 0.4 }}
          className="mt-12 text-center text-sm text-[color:var(--text-secondary)] max-w-2xl mx-auto"
        >
          {/*
            Both facts used to sit in a banner across the top of every template
            page. They belong here instead: a disclaimer strip is the first
            thing a buyer sees on work meant to sell them, and it made the
            example look like a draft. Said once, on the page doing the selling.
          */}
          Every example is a fictional business, built from the same template a
          real order is produced from, and the colours you see are ours —{" "}
          <span className="text-[color:var(--text-primary)]">
            your palette and logo are set from your own brand when the site is
            built
          </span>
          . Need more than one page, or something the template does not cover?
          That is a{" "}
          <Link href="/#pricing" className="text-[color:var(--accent)] underline">
            Professional build
          </Link>
          .
        </motion.p>
      </div>
    </section>
  );
}
