import type { DesignComponentDefinition } from "./types";
import { endingContracts } from "../composition/ending-contracts";
import { endingSectionIds } from "../composition/ending-schemas";
const names={"cta.editorial":"Editorial Conversion","cta.signal":"Signal Conversion","contact.inquiry":"Inquiry & Contact","footer.sitemap":"Sitemap Footer","footer.compact":"Compact Footer","footer.split":"Split Footer","footer.banner":"Banner Footer","work.expand-rail":"Expanding Image Rail","work.card-rail":"Editorial Card Rail","work.glass-lens":"Glass Lens Gallery"};
export const endingSections=endingSectionIds.map(id=>{
  const contract=endingContracts[id];
  const configurations=[{name:"adaptation",options:["architecture","creator","hospitality"]},{name:"contentLength",options:["standard","long"]},{name:"structure",options:contract.variants},{name:"motion",options:contract.motion},...contract.configuration];
  const defaults=Object.fromEntries(configurations.map(field=>[field.name,field.options[0]]));
  return {id,name:names[id],category:contract.category,description:contract.structuralDNA,composition:contract,sourceConcept:"readiness-user-supplied-21st-dev",styles:["neutral","editorial","technical"],pageTypes:["home","contact","landing","standard","portfolio-index","project-detail"],supportedMotion:contract.motion,complexity:"medium",mobileReady:true,accessibilityReady:true,responsiveReady:{desktop:true,tablet:true,mobile:true},status:"production",version:"1.0.0",productionEvidence:{responsive:{desktop:true,tablet:true,mobile:true},accessibility:{semantics:true,keyboard:true,focus:true,reducedMotion:true},performanceReviewed:true,brandNeutralReviewed:true,visualDiversityReviewed:true,approvedBy:"User requested production import; see readiness-import verification",approvedAt:"2026-10-06T18:00:00-04:00"},defaultCreative:{typography:id==="cta.signal"?"poster":"neo-grotesk",artDirection:id==="cta.signal"?"billboard":"publication",motion:"restrained"},configurations,previewVariants:[{id:"default",label:"Native structure",config:defaults},{id:"alternative",label:"Alternative structure / creator",config:{...defaults,adaptation:"creator",structure:contract.variants[1]??contract.variants[0],surface:"surface",motion:contract.motion[1]??"none"}}]} as const satisfies DesignComponentDefinition;
});
