import coast from "@/docs/design-engine/creative-calibration-002/assets/coastal-architecture.jpg";
import performer from "@/docs/design-engine/creative-calibration-002/assets/stage-performer.jpg";
import type { SceneContent } from "./FullViewportHero";
const src=(asset:typeof coast)=>typeof asset==="string"?asset:asset.src;
export const immersiveContexts = [
 {name:"Architecture",brand:"COMMON / GROUND",typography:"luxury",posterTypography:"geometric",art:"gallery",content:{eyebrow:"Architecture, held in landscape",title:"A quieter\nkind of presence.",description:"Places shaped by their surroundings, and by the lives unfolding within them.",reference:"Common / Ground · Selected places",caption:"Coastal residence / A study in light",action:{label:"Explore the places",href:"#hx-next"},image:{src:src(coast),alt:"Limestone residence facing a coastal horizon; generated study image",width:1800,height:1013,focal:{x:65,y:45},mobileFocal:{x:72,y:45}}}},
 {name:"Independent apparel",brand:"OFF HOURS",typography:"fashion",posterTypography:"poster",art:"runway",content:{eyebrow:"Independent apparel / Edition 06",title:"Own the\nafter hours.",description:"An everyday uniform with a different rhythm. Find the pieces that feel like you.",reference:"Off Hours · Edition 06",caption:"The evening edit / Illustrative campaign",action:{label:"Explore the edit",href:"#hx-next"},image:{src:"/design-engine-study-007/fashion-campaign.webp",alt:"Independent apparel campaign with an urban street setting; generated study image",width:1536,height:1024,focal:{x:55,y:42},mobileFocal:{x:60,y:40}}}},
 {name:"Performance ensemble",brand:"ROOM ENSEMBLE",typography:"humanist",posterTypography:"brutalist",art:"billboard",content:{eyebrow:"An independent performance ensemble",title:"Leave room\nfor the unexpected.",description:"New movement, new voices, and the space between a gesture and its audience.",reference:"Room Ensemble · Season studies",caption:"In rehearsal / Illustrative performance study",action:{label:"Discover the program",href:"#hx-next"},image:{src:src(performer),alt:"Performer reaching into a beam of stage light; generated study image",width:1800,height:1013,focal:{x:50,y:40},mobileFocal:{x:50,y:40}}}},
] as const;
export function immersiveFixture(adaptation=0,id="hx-opening"):SceneContent{return {...immersiveContexts[adaptation].content,id};}
