"use client";
import { useState, type ReactNode } from "react";
import { DesignThemeProvider } from "../../foundations/DesignThemeProvider";
import { collection004, storyAdaptations, type StoryStudy } from "./fixtures";
import { collection004Review } from "./review";
import { StoryStudyArtwork } from "./Study";
import { LabEditor } from "../editor/LabEditor";

export function CollectionGallery({ toolbar, workspaceSwitch, onInspect }: { toolbar?: ReactNode; workspaceSwitch?: ReactNode; onInspect: (id: "story.object-biography" | "story.working-conversation" | "story.decision-ledger") => void }) {
  const [selected, setSelected] = useState("S01"), [adaptation, setAdaptation] = useState(0), [device, setDevice] = useState("desktop"), [overview, setOverview] = useState(false), [tab, setTab] = useState("study");
  const study = collection004.find(s => s.id === selected)!;
  const render = (s: StoryStudy) => <DesignThemeProvider typography={s.typography} artDirection={s.art} motion="none" overrides={{ color: { background: s.palette[0], surface: s.palette[0], surfaceElevated: s.palette[0], foreground: s.palette[1], muted: s.palette[1], accent: s.palette[2], accentForeground: s.palette[0], border: s.palette[1] } }}><StoryStudyArtwork study={s} adaptation={storyAdaptations[adaptation]} /></DesignThemeProvider>;
  const candidate = selected === "S01" ? "story.object-biography" : selected === "S03" ? "story.working-conversation" : selected === "S06" ? "story.decision-ledger" : null;
  return <LabEditor title="Design Lab" workspaceSwitch={workspaceSwitch} toolbar={toolbar} canvasWidth={overview ? 1440 : device === "mobile" ? 390 : device === "tablet" ? 768 : 1440} resetKey={`${selected}-${overview}-${adaptation}`} activeTab={tab} onTabChange={setTab}
    tabs={[
      { id: "study", label: "Study", content: <><header className="calibration-intro"><h2>Collection 004 · Brand / Story</h2><p>Eight body-section studies. Human creative review recorded · 30 September 2026. All artwork is complete with motion none.</p></header><div className="calibration-controls">
        <label>Story study<select aria-label="Story study" disabled={overview} value={selected} onChange={e => setSelected(e.target.value)}>{collection004.map(s => <option key={s.id} value={s.id}>{s.id} · {s.name} — {collection004Review[s.id].status}</option>)}</select></label>
        <label>Client adaptation<select aria-label="Client adaptation" value={adaptation} onChange={e => setAdaptation(Number(e.target.value))}>{storyAdaptations.map((a, i) => <option key={a.client} value={i}>{a.client} · {a.context.replace("Imagined ", "")}</option>)}</select></label>
        <label>Client artboard<select aria-label="Client artboard" disabled={overview} value={device} onChange={e => setDevice(e.target.value)}><option value="desktop">Desktop · 1440px</option><option value="tablet">Tablet · 768px</option><option value="mobile">Mobile · 390px</option></select></label>
        <button type="button" aria-pressed={overview} onClick={() => setOverview(value => !value)}>Compare eight studies</button>
      </div><p className="story-review-status"><strong>{collection004Review[study.id].status}</strong><br />{collection004Review[study.id].note} {collection004Review[study.id].revision}<br />{study.typography} typography / {study.art} art direction. Fixed for this authored study. Explore supported layers on the separate reusable implementation in the Component catalog.</p>
      {candidate ? <button type="button" onClick={() => onInspect(candidate)}>Inspect experimental {selected} implementation ↗</button> : null}<p className="lab-layer-note">Three unrelated imagined briefs share each mechanism. Names and copy are illustrative; no client facts, awards or testimonials are asserted.</p></> },
      { id: "rationale", label: "Rationale", content: <><h2>{study.id} · {study.name}</h2><dl className="story-notes">{[["Visitor purpose", study.purpose], ["Structural / narrative DNA", study.dna], ["Required content", study.content], ["Media and crop", study.media], ["Desktop / tablet / mobile", study.responsive], ["Implemented vs proposed", study.interaction], ["Candidate contract", study.candidate], ["Nearest concepts", study.nearest]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></> },
      { id: "review", label: "Review", content: <div className="story-notes"><h2>Implementation shortlist</h2><p>S01, S03 and S06 have separate reusable experiments with strict client schemas. Their creative directions are now approved; their implementations remain experimental. S05 is rejected and retained only as historical study. S04’s requested arrow fix is ready for confirmation.</p><p>Design → Component catalog exposes adaptations, content extremes and declared layers. Composition → 004 F–K contains two unlike tests per candidate, beside existing Navigation, Hero and Feature List systems.</p><p>All eight original studies stay here, outside registry inventory. Unimplemented interactions are described only as proposals.</p><p>Compare S01/S05 (one dossier vs two inheritances), S02/S06 (spoken beliefs vs weighed decisions), S03/S07 (turn-taking vs one author), S04/S08 (recurrence vs handoff). Typography, image roles and density reinforce these mechanisms.</p><p>Sources: retained generated assets from Creative Collection 001 and Calibration 002. No new image generation or claim of documentary photography. Their original attribution records are preserved.</p></div> },
    ]}>
    {overview ? <div className="story-overview">{collection004.map(s => <article key={s.id}><h3>{s.id} · {s.name} / {collection004Review[s.id].status}</h3><div className="story-overview-stage">{render(s)}</div></article>)}</div> : render(study)}
  </LabEditor>;
}
