import chair from "@/docs/design-engine/creative-calibration-002/assets/metal-chair-portrait.jpg";
import coast from "@/docs/design-engine/creative-calibration-002/assets/coastal-architecture.jpg";
import stone from "@/docs/design-engine/creative-calibration-002/assets/coastal-stone-detail.jpg";
import stage from "@/docs/design-engine/creative-calibration-002/assets/stage-performer.jpg";
import portrait from "@/docs/design-engine/creative-collection-001/assets/portrait-study.jpg";
import type { SectionImage } from "../../media/types";
import type { TypographyProfileId } from "../../foundations/typography/profiles";
import type { ArtDirectionId } from "../../foundations/art-direction";

const media = (asset: typeof chair, alt: string): SectionImage => ({ src: typeof asset === "string" ? asset : asset.src, width: asset.width || 1800, height: asset.height || 1200, alt: `${alt}. Generated study image; not a client record.`, focal: { x: 50, y: 45 }, mobileFocal: { x: 50, y: 45 } });
export const storyMedia = {
  object: media(chair, "Brushed metal chair in a stone room"), place: media(coast, "Low stone building and coastal horizon"), detail: media(stone, "Close view of textured limestone"), movement: media(stage, "Performer reaching into stage light"), person: media(portrait, "Portrait used as an illustrative human presence"),
};
export type StoryAdaptation = {
  client: string; context: string; title: string; deck: string; subject: string; origin: string; continuation: string;
  object: SectionImage; second: SectionImage; fragments: readonly [string, string, string];
  records: readonly { label: string; title: string; body: string }[];
  exchanges: readonly { question: string; speaker: string; role: string; answer: string; aside: string }[];
  decisions: readonly { belief: string; tension: string; practice: string; rationale: string }[];
};
/** Invented briefs and illustrative copy only; no assertion about a real client. */
export const storyAdaptations: readonly StoryAdaptation[] = [
  {
    client: "Common Form", context: "Imagined furniture repair workshop", title: "A chair is never just a chair.", deck: "A way of thinking about the things we choose to keep.", subject: "The first object", origin: "A loose joint. A useful question.", continuation: "What else could stay in use?", object: storyMedia.object, second: storyMedia.detail,
    fragments: ["Keep the useful.", "Question the perfect.", "Leave room for repair."],
    records: [{ label: "What we noticed", title: "The mark of a hand", body: "A worn edge can tell us where a thing has been held. The brief begins by looking, before deciding what to change." }, { label: "What we chose", title: "A joint you can reach", body: "Make the connection legible. An object should be possible to understand, take apart and care for." }, { label: "What continues", title: "Another working life", body: "The repair becomes one chapter in a longer relationship between an object and its keeper." }],
    exchanges: [{ question: "What deserves to stay?", speaker: "The keeper", role: "A point of view", answer: "The part that makes it ours. Even when it is the part a photograph would crop out.", aside: "Illustrative conversation for this imagined brief; not a customer quotation." }, { question: "And what needs to change?", speaker: "The maker", role: "A working response", answer: "The part that keeps it from being useful. We can change a joint without erasing the years around it.", aside: "A real project would replace these voices with approved, attributed words." }],
    decisions: [{ belief: "Keep it useful", tension: "Patina / performance", practice: "Repair the joint; keep the worn edge.", rationale: "Visible wear and structural failure are different questions. Document both before choosing the treatment." }, { belief: "Make it legible", tension: "Finish / access", practice: "Let the next person reach the fixing.", rationale: "A concealed fixing can make a future repair harder. The client decides which compromises the object can carry." }, { belief: "Leave a record", tension: "Ownership / continuity", practice: "Pass on the care notes with the object.", rationale: "A short, useful record helps the next keeper understand what changed and why." }],
  },
  {
    client: "Open Room", context: "Imagined community learning space", title: "A room begins with listening.", deck: "An invitation to take part in shaping a shared place.", subject: "The open door", origin: "An empty room. A first conversation.", continuation: "Who is still missing from the table?", object: storyMedia.place, second: storyMedia.person,
    fragments: ["Listen before planning.", "Make space to try.", "Keep the door open."],
    records: [{ label: "What we noticed", title: "The threshold", body: "The first step into a room can be the hardest. An invitation needs to explain what will happen and who can take part." }, { label: "What we chose", title: "A place to begin", body: "A shared table makes room for questions before anyone is expected to know the answer." }, { label: "What continues", title: "A different gathering", body: "Each new group brings a different way of using the space. The room should be able to learn from them." }],
    exchanges: [{ question: "Who gets to begin?", speaker: "A new participant", role: "A point of view", answer: "Someone who is curious, even if they do not yet know what they want to make.", aside: "An invented voice for the study, not a testimonial or a report of participation." }, { question: "What makes that possible?", speaker: "The host", role: "A working response", answer: "A clear welcome, time to ask, and permission to start again. The first attempt is part of the work.", aside: "Replace this proposed voice with words approved by the people involved." }],
    decisions: [{ belief: "Make a welcome", tension: "Structure / freedom", practice: "Explain the session; leave room for questions.", rationale: "Knowing what happens next can make it easier to take part without requiring everyone to follow the same path." }, { belief: "Share the room", tension: "Experience / access", practice: "Let a new voice lead the next question.", rationale: "Familiarity is useful, but should not become the only way into a conversation." }, { belief: "Keep learning", tension: "Plan / response", practice: "Ask what the room needs after each gathering.", rationale: "The schedule is a starting proposal, open to what participants choose to share." }],
  },
  {
    client: "Field Signal", context: "Imagined environmental research practice", title: "A question worth returning to.", deck: "Observation connects an idea to the place it is meant to describe.", subject: "The field note", origin: "One observation. More than one reading.", continuation: "What would change our understanding?", object: storyMedia.detail, second: storyMedia.place,
    fragments: ["Observe before naming.", "Show the uncertainty.", "Return to the question."],
    records: [{ label: "What we noticed", title: "A change in surface", body: "The same material can look different with light, weather and distance. A note needs its context." }, { label: "What we chose", title: "A traceable method", body: "Record how the observation was made so another person can understand its limits." }, { label: "What continues", title: "A question reopened", body: "A later observation may change the interpretation. Keep the earlier reading visible rather than writing over it." }],
    exchanges: [{ question: "What does the observation tell us?", speaker: "The observer", role: "A point of view", answer: "Something about this place, at this moment, through the method we chose.", aside: "Illustrative research dialogue only. No measured result or professional claim is asserted." }, { question: "And what remains uncertain?", speaker: "The reviewer", role: "A working response", answer: "What we would see at another time, or through another method. The useful next step is to make that uncertainty explicit.", aside: "Use actual approved research notes and attribution in a client adaptation." }],
    decisions: [{ belief: "Show the method", tension: "Clarity / complexity", practice: "Keep the context beside the observation.", rationale: "A legible summary should still make the underlying method and its limits available." }, { belief: "Name the limits", tension: "Signal / uncertainty", practice: "Record what the observation cannot establish.", rationale: "A stated boundary helps people decide whether the finding answers their question." }, { belief: "Stay revisable", tension: "Continuity / correction", practice: "Keep a record of changed interpretations.", rationale: "A new reading can be useful without pretending the earlier one never existed." }],
  },
];
export type StoryStudy = {
  id: "S01" | "S02" | "S03" | "S04" | "S05" | "S06" | "S07" | "S08"; name: string; typography: TypographyProfileId; art: ArtDirectionId;
  palette: readonly [string, string, string]; purpose: string; dna: string; content: string; media: string; responsive: string; interaction: string; candidate: string; nearest: string;
};
export const collection004 = [
  { id: "S01", name: "Object biography", typography: "editorial", art: "publication", palette: ["#eee9df", "#302a25", "#8b4129"], purpose: "Understand an origin through a tangible thing and the decisions it carries.", dna: "An artifact occupies the center of an annotated dossier. Three numbered observations orbit its edges; an origin-to-continuation sentence closes the record.", content: "One real artifact or place, three observations, an origin and a continuing question. No invented dates or provenance.", media: "One source image with alt, dimensions and authored focal points. Portrait/emphasis or contained crop; keep the object complete. Attribution in caption.", responsive: "Desktop: title, object with side records, continuation. Tablet: narrower object plus records. Mobile: title → object → three records → continuation. DOM order is constant.", interaction: "Study is fully static. Candidate implements the same reading surface; no hotspots or hover-only notes.", candidate: "story.object-biography · two structures · image treatments · none · publication/gallery/precision/runway spatial support", nearest: "H23 also values an object, but S01 is a body dossier of observations rather than an edition Hero; H27 keeps one margin whereas this uses several authored records." },
  { id: "S02", name: "The manifesto fold", typography: "poster", art: "billboard", palette: ["#e5f074", "#242920", "#424d2b"], purpose: "Make a set of beliefs memorable and give each a practical meaning.", dna: "Three large statements occupy alternating full-width folds; each is interrupted by one small explanation. A continuous argument, not a card set.", content: "Exactly three concise beliefs and their practical explanations; a shared introductory line.", media: "Type only. No image or icon requirement; the hierarchy must stand without decoration.", responsive: "Desktop: long fold / inset fold / long fold. Tablet keeps alternating indentation. Mobile removes indentation and reads top to bottom.", interaction: "No interaction or animation implemented. Optional future print/export is a proposal only.", candidate: "Potential: three-clause schema; fixed fold; all type roles; billboard/publication; none; no media.", nearest: "S06 turns beliefs into inspectable tradeoffs; S02 is a spoken argument. H19 is an event bill, with date/program rather than beliefs." },
  { id: "S03", name: "Working conversation", typography: "humanist", art: "salon", palette: ["#e4eade", "#243b32", "#3e6451"], purpose: "Meet a practice through the questions and perspectives that shape its work.", dna: "A question crosses the page, answered by a named role in an offset transcript lane. Successive exchanges make a conversation with visible turns.", content: "Two to four approved questions, speakers, roles and answers. Fixtures are explicitly invented dialogue, never testimonials.", media: "No media required. A conversation must be legible without portraits or stock people.", responsive: "Desktop: broad question → narrow speaker gutter → answer. Tablet retains speaker gutter. Mobile stacks question, speaker, answer, attribution before next turn.", interaction: "Study/candidate are static transcripts. A future audio reading is proposed, not a working play button.", candidate: "story.working-conversation · transcript/roundtable · no media · none · salon/publication/precision/gallery", nearest: "S07 is one sustained letter; this alternates questions and voices. H20 is a first-screen invitation, not an attributed exchange." },
  { id: "S04", name: "A practice in orbit", typography: "geometric", art: "precision", palette: ["#e2eaf1", "#203548", "#315f8b"], purpose: "Explain why a process returns to its starting question.", dna: "Four stations share a circular route around one constant question. The return link is the narrative; no claim of linear completion.", content: "A central question, four named steps and a meaningful return relationship.", media: "Code-native diagram, no photograph. All diagram labels also appear in semantic ordered text.", responsive: "Desktop: orbit beside a short key. Tablet retains the orbit above key. Mobile converts to numbered reading list and a small still loop; no horizontal pan.", interaction: "Static diagram only. Keyboard station highlighting is a possible future experiment, not implemented.", candidate: "Potential: four-step cycle schema; fixed orbit; geometric/technical/humanist; precision/publication; none; semantic SVG plus list.", nearest: "H24 exposes physical parts; S04 explains recurrence. S08 is an irreversible handoff, so it should never be drawn as a loop." },
  { id: "S05", name: "Two inheritances", typography: "luxury", art: "gallery", palette: ["#efe8e0", "#45332c", "#785145"], purpose: "Show what a practice receives and what it chooses to carry forward.", dna: "Unequal photographic shelves are connected by a shared verbal hinge. Origin and continuation remain distinct readings, not an interactive before/after.", content: "Two related images, two clear captions and one bridge statement. Avoid unsupported heritage dates.", media: "Two independently cropped sources. Broad first shelf and tighter second; never imply identical camera registration. Author focal points and credit both.", responsive: "Desktop: wide first shelf, hinge, inset second shelf. Tablet preserves unequal widths. Mobile reads first caption/image → hinge → second caption/image.", interaction: "Static; no wipe, auto-crossfade or drag comparison. Optional future source links are proposed.", candidate: "Potential: paired-story schema; fixed shelves; luxury/editorial/humanist; gallery/publication; none; two independently authored images.", nearest: "H12 is a registered visual comparison; S05 explicitly is not. S01 examines one object, while this binds two moments with an inheritance." },
  { id: "S06", name: "The decision ledger", typography: "technical", art: "precision", palette: ["#f1f0e8", "#26322d", "#436551"], purpose: "Understand a belief through its tensions and observable working choices.", dna: "A continuous ruled ledger aligns principle, tension and practice. Rationale sits under the decision it qualifies; no score or invented proof.", content: "Two to five principles with a real tradeoff, a working choice and a rationale. Client must approve the promises.", media: "Type only; rules express relationships, not a decorative grid.", responsive: "Desktop: three aligned ledger columns. Tablet keeps three at readable widths. Mobile each numbered record becomes principle → tension → practice → rationale.", interaction: "Study shows the complete open ledger. Candidate additionally implements native rationale disclosures (Enter/Space, visible focus), with no animation.", candidate: "story.decision-ledger · open/disclosure · no media · none · precision/publication/billboard", nearest: "Feature List is a collection of independent cards. This binds three comparison dimensions row by row. S02 voices beliefs without weighing a tradeoff." },
  { id: "S07", name: "A letter, still open", typography: "fashion", art: "runway", palette: ["#eee1e7", "#4a2940", "#79435f"], purpose: "Let a visitor read one sustained, personal explanation of intent.", dna: "An expansive salutation opens a narrow letter column. An indented second thought and a detached postscript slow the cadence before the sign-off.", content: "One approved author or collective voice, salutation, two paragraphs, sign-off and postscript. Do not simulate a real signature.", media: "No media. Typography, line measure and pauses carry the correspondence.", responsive: "Desktop: salutation across field, inset letter, side postscript. Tablet contracts the pause. Mobile reads salutation → paragraphs → sign-off → postscript.", interaction: "Static complete letter; no typewriter, scroll gate or fake signature animation.", candidate: "Potential: letter schema; fixed letter; fashion/editorial/humanist; runway/publication; none; no media.", nearest: "S03 is multi-voice and turn-based; S07 is one author in a continuous reading column. H27 is evidence-led and would lose its purpose without the source margin." },
  { id: "S08", name: "Material relay", typography: "brutalist", art: "billboard", palette: ["#d55c32", "#251f1b", "#251f1b"], purpose: "Follow a material or idea as responsibility passes from one step to another.", dna: "Three adjacent image slices make a single contact strip, crossed by oversized handoff verbs. A common caption rail ties each slice to its responsibility.", content: "Three stages with distinct responsibility, image and verb; preserve causal sequence.", media: "These fixtures use three authored crops of one source object, not documentary process records. A client can supply three related stage images. Each slice has a separate accessible caption and focal point; detail is intentional.", responsive: "Desktop: uninterrupted triptych and caption rail. Tablet retains strip with smaller verbs. Mobile folds into three consecutive image/caption records.", interaction: "Static relay. A later source-inspection interaction is a proposal only; images are not fake buttons.", candidate: "Potential: three-stage relay schema; fixed strip; brutalist/poster/technical; billboard/precision; none; three image records.", nearest: "S05 connects two open-ended inheritances; S08 is a specific three-stage transfer. S04 returns to its beginning whereas this hands off forward." },
] as const satisfies readonly StoryStudy[];
