import { createRequire } from "node:module";
import fs from "node:fs";
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || "/Users/belierjavier/.npm/_npx/e41f203b7505f1fb/node_modules/playwright");
const origin = process.env.CREATORS_TEST_URL || "http://127.0.0.1:4318";
const output = "docs/campaigns/evidence";
fs.mkdirSync(output, { recursive: true });
const browser = await chromium.launch({ executablePath: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", headless: true });
const context = await browser.newContext();
const errors = [], results = [], events = [], availability = {};
await context.exposeBinding("recordCampaignEvent", (_source, event) => { events.push(event); });
const record = (name, pass, detail) => { results.push({ name, pass, detail }); if (!pass) throw new Error(`${name}: ${detail ?? "failed"}`); };
await context.route("**/_vercel/insights/script.js*", route => route.fulfill({ status: 200, contentType: "text/javascript", body: "" }));
await context.route("**/_vercel/speed-insights/script.js*", route => route.fulfill({ status: 200, contentType: "text/javascript", body: "" }));
await context.addInitScript(() => {
  window.__campaignEvents = [];
  window.va = (kind, value) => { if (kind === "event") { window.__campaignEvents.push(value); void window.recordCampaignEvent(value); } };
});
const page = await context.newPage();
page.on("pageerror", e => errors.push(e.message));
page.on("console", msg => { if (msg.type() === "error" && !msg.text().includes("Content Security Policy") && !msg.text().includes("Content-Security-Policy")) errors.push(msg.text()); });
const campaignUrl = `${origin}/creators?utm_source=qa_creator&utm_medium=social&utm_campaign=launch&ref=creator-ref`;
try {
  for (const width of [320, 375, 430, 768, 1366, 1440]) {
    await page.setViewportSize({ width, height: width === 320 ? 568 : width === 430 ? 932 : width === 768 ? 1024 : width === 1366 ? 768 : width === 1440 ? 900 : 812 });
    const response = await page.goto(campaignUrl, { waitUntil: "domcontentloaded" });
    await page.getByRole("heading", { level: 1 }).waitFor();
    await page.waitForFunction(() => document.querySelector('a[href*="vigil_campaign"]'));
    await page.evaluate(async () => { await document.fonts.ready; });
    await page.addStyleTag({ content: '.star-cursor-el { display: none !important; }' });
    record(`${width}: white hero with centered copy`, await page.getByRole("heading", { level: 1 }).evaluate(el => getComputedStyle(el).textAlign === "center" && getComputedStyle(el.closest("section")).backgroundColor === "rgb(255, 255, 255)"));
    record(`${width}: seven generated creator photos below centered copy`, await page.locator('[data-creator-collage] img').count() === 7 && await page.locator('[data-creator-collage]').evaluate(el => el.getBoundingClientRect().top > document.querySelector('h1').getBoundingClientRect().bottom));
    await page.waitForFunction(() => [...document.querySelectorAll('[data-creator-collage] img')].every(img => img.complete && img.naturalWidth > 0));
    record(`${width}: collage assets load with responsive sources`, await page.locator('[data-creator-collage] img').evaluateAll(els => els.every(el => el.currentSrc.includes('/creators/collage/') && el.srcset.includes('300w') && el.naturalWidth > 0)));
    record(`${width}: hero and photos use slower entrance motion`, await page.getByRole('heading', { level: 1 }).evaluate(el => parseFloat(getComputedStyle(el.parentElement).animationDuration) >= 1.5) && await page.locator('[data-collage-float] > div').evaluateAll(els => els.every(el => parseFloat(getComputedStyle(el).animationDuration) >= 1.8)));
    record(`${width}: hero fills viewport and scroll cue fits`, await page.locator('#site-root section').first().evaluate(el => { const r = el.getBoundingClientRect(); return Math.abs(r.bottom - innerHeight) <= 2; }));
    record(`${width}: scroll cue visible above fold`, await page.getByRole("link", { name: "Scroll to find your fit", exact: true }).evaluate(el => el.getBoundingClientRect().bottom <= innerHeight));
    record(`${width}: CTA follows shared site styling with campaign tokens`, await page.getByRole("link", { name: "Find your website", exact: true }).evaluate(el => { const css = getComputedStyle(el); return css.backgroundColor === "rgb(150, 81, 108)" && css.color === "rgb(255, 255, 255)" && css.borderRadius === "8px" && el.classList.contains('btn-primary'); }));
    record(`${width}: light editorial palette`, await page.evaluate(() => getComputedStyle(document.body).backgroundColor === "rgb(255, 255, 255)" && getComputedStyle(document.querySelector("nav")).color !== "rgb(245, 245, 243)"));
    record(`${width}: creator editorial font loaded`, await page.getByRole("heading", { level: 1 }).evaluate(el => /Bodoni/.test(getComputedStyle(el).fontFamily) && document.fonts.status === "loaded"));
    record(`${width}: flat backgrounds without gradients`, await page.locator("#site-root").evaluate(el => [...el.querySelectorAll("*")].filter(node => node.getBoundingClientRect().width > 0).every(node => !getComputedStyle(node).backgroundImage.includes("gradient("))));
    record(`${width}: HTTP 200`, response.status() === 200);
    record(`${width}: no page or inner-scroller overflow`, await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1 && document.querySelector("#site-root").scrollWidth <= innerWidth + 1));
    record(`${width}: three compact campaign sections`, await page.locator('#site-root section').count() === 3);
    const ctas = page.locator('#site-root a[href*="vigil_campaign"]');
    record(`${width}: all six campaign links meet 44px touch target`, await ctas.evaluateAll(elements => elements.length === 6 && elements.every(el => el.getBoundingClientRect().height >= 44)));
    record(`${width}: banner and navigation do not overlap`, await page.locator('.creator-promo-banner').evaluate(el => el.getBoundingClientRect().bottom <= document.querySelector('nav').getBoundingClientRect().top + 1));
    record(`${width}: canonical prices have 15% discount`, await page.getByText("$509.15", { exact: true }).count() === 1 && await page.getByText("$1,274.15", { exact: true }).count() === 1 && await page.locator('del').allTextContents().then(values => values.includes("$599") && values.includes("$1,499")));
    record(`${width}: prices have campaign color`, await page.getByText('$509.15', { exact: true }).evaluate(el => getComputedStyle(el).color === 'rgb(150, 81, 108)'));
    record(`${width}: banner uses Vigil font and identifies creators/influencers`, await page.locator('.creator-promo-link').evaluate(el => /Space[ _]Grotesk/.test(getComputedStyle(el).fontFamily) && el.textContent.includes('creators and influencers')));
    record(`${width}: startup video is deferred before spotlight`, await page.locator('[data-creator-preview] video').getAttribute('src') === null);
    await page.waitForFunction(() => document.querySelectorAll('[data-reaction]').length > 0);
    await page.waitForTimeout(2200);
    await page.screenshot({ path: `${output}/creators-${width}-hero.png` });
    await page.getByRole("link", { name: "Find your website", exact: true }).click();
    await page.waitForTimeout(350);
    const y = await page.locator("#choose-your-site").evaluate(el => el.getBoundingClientRect().top);
    record(`${width}: hero CTA exposes both offers below navigation/banner`, y >= 100 && y < 220, y);
    await page.waitForTimeout(1300);
    await page.screenshot({ path: `${output}/creators-${width}-offers.png` });
    await page.locator('img[alt*="Scar"]').scrollIntoViewIfNeeded();
    await page.waitForFunction(() => [...document.querySelectorAll('#site-root img')].every(img => img.complete && img.naturalWidth > 0));
    record(`${width}: actual Scar portfolio has a high-resolution poster`, await page.locator('img[alt*="Scar"]').evaluate(el => el.naturalWidth >= 1920));
    record(`${width}: Scar spotlight reserves a full viewport`, await page.locator('#creator-spotlight').evaluate(el => el.getBoundingClientRect().height >= innerHeight - 45));
    await page.waitForFunction(() => { const v = document.querySelector('[data-creator-preview] video'); return v.readyState >= 2 && v.currentTime > .1 && !v.paused; });
    record(`${width}: real project startup plays on entry`, await page.locator('[data-creator-preview] video').evaluate(el => el.muted && el.playsInline && el.currentSrc.endsWith('scarlen-startup.mp4')));
    record(`${width}: project video has a crisp high-resolution source`, await page.locator('[data-creator-preview] video').evaluate(el => el.videoWidth >= 1920 && el.videoHeight >= 1190));
    await page.waitForFunction(() => document.querySelector('[data-creator-preview] video').ended);
    await page.screenshot({ path: `${output}/creators-${width}-spotlight.png` });
    // The site's nested scroll root needs temporary overflow expansion for a whole-page capture.
    const captureStyle = await page.addStyleTag({ content: 'html, body { height: auto !important; overflow: visible !important; } #site-root { height: auto !important; max-height: none !important; overflow: visible !important; }' });
    await page.screenshot({ path: `${output}/creators-${width}-full.png`, fullPage: true });
    await captureStyle.evaluate(el => el.remove());
    record(`${width}: campaign/main click hooks`, await page.evaluate(() => window.__campaignEvents.some(e => e.name === "creator_campaign_cta_click" && e.data?.placement === "hero")));
  }
  await page.goto(campaignUrl, { waitUntil: "domcontentloaded" });
  await page.waitForFunction(() => document.querySelectorAll('[data-reaction]').length > 0);
  await page.evaluate(() => {
    window.__positions = [];
    window.__reactionObserver = new MutationObserver(records => records.forEach(r => r.addedNodes.forEach(node => {
      if (node instanceof HTMLElement && node.hasAttribute('data-reaction')) window.__positions.push({ id: node.dataset.reaction, x: node.style.left, y: node.style.top });
    })));
    window.__reactionObserver.observe(document.querySelector('[data-creator-reactions]'), { childList: true });
  });
  await page.waitForFunction(() => window.__positions.length >= 5);
  record("social reactions appear at varying random positions", await page.evaluate(() => new Set(window.__positions.map(p => `${p.x}/${p.y}`)).size >= 5));
  record("social reactions animate without invented counts", await page.locator('[data-reaction]').evaluateAll(els => els.length > 0 && els.length <= 6 && els.every(el => getComputedStyle(el).animationName !== "none" && !/\d/.test(el.textContent))));
  record('hero pause/resume control is removed', await page.getByRole('button', { name: 'Pause animation', exact: true }).count() === 0 && await page.getByRole('button', { name: 'Resume animation', exact: true }).count() === 0);
  record("collage images float alongside reactions", await page.locator('[data-collage-float]').evaluateAll(els => els.length === 7 && els.every(el => getComputedStyle(el).animationName !== 'none' && getComputedStyle(el).animationPlayState === 'running')));
  await page.locator('img[alt*="Scar"]').scrollIntoViewIfNeeded();
  await page.waitForFunction(() => document.querySelector('[data-creator-collage]').getBoundingClientRect().bottom < 0);
  await page.waitForTimeout(300);
  const offscreen = await page.evaluate(() => window.__positions.length);
  await page.waitForTimeout(1400);
  record("offscreen hero stops generating reactions", await page.evaluate(n => window.__positions.length === n, offscreen));
  record('offscreen collage suspends its floats automatically', await page.locator('[data-collage-float]').evaluateAll(els => els.every(el => getComputedStyle(el).animationPlayState === 'paused')));
  await page.evaluate(() => window.__reactionObserver.disconnect());
  await page.getByRole('button', { name: 'Pause project animation', exact: true }).click();
  record('project playback pauses', await page.locator('[data-creator-preview] video').evaluate(el => el.paused));
  await page.evaluate(() => document.dispatchEvent(new Event('visibilitychange')));
  await page.waitForTimeout(150);
  record('manual project pause survives visibility synchronization', await page.locator('[data-creator-preview] video').evaluate(el => el.paused));
  await page.getByRole('button', { name: 'Resume project animation', exact: true }).click();
  await page.waitForFunction(() => !document.querySelector('[data-creator-preview] video').paused);
  record('project playback resumes', await page.locator('[data-creator-preview] video').evaluate(el => !el.paused));
  await page.waitForFunction(() => document.querySelector('[data-creator-preview] video').ended);
  await page.getByRole('button', { name: 'Replay project animation', exact: true }).click();
  record('project intro can replay', await page.locator('[data-creator-preview] video').evaluate(el => !el.paused && el.currentTime < 2));
  await page.getByRole('link', { name: 'Find your website', exact: true }).scrollIntoViewIfNeeded();
  await page.waitForTimeout(250);
  record('project playback stops offscreen', await page.locator('[data-creator-preview] video').evaluate(el => el.paused));
  await page.mouse.move(500,150);
  record('promotion banner loops', await page.locator('.creator-promo-track').evaluate(el => getComputedStyle(el).animationName === 'creatorPromoLoop' && getComputedStyle(el).animationIterationCount === 'infinite'));
  await page.getByRole('button', { name: 'Pause promotion banner', exact: true }).click();
  record('banner pause control', await page.locator('.creator-promo-track').evaluate(el => getComputedStyle(el).animationPlayState === 'paused'));
  await page.getByRole('button', { name: 'Resume promotion banner', exact: true }).click();
  await page.getByRole('link', { name: 'Find your website', exact: true }).focus();
  await page.mouse.move(500,150);
  record('banner resume control', await page.locator('.creator-promo-track').evaluate(el => getComputedStyle(el).animationPlayState === 'running'));
  await page.getByRole('link', { name: 'Find your website', exact: true }).click();
  await page.locator('.creator-promo-link').click();
  await page.waitForURL(/#creator-hero$/);
  record('same-page banner returns to hero', await page.locator('#site-root').evaluate(el => el.scrollTop <= 50));
  await page.locator('.creator-promo-link').focus();
  record('clicked/focused/hovered banner keeps moving', await page.locator('.creator-promo-track').evaluate(async el => { const animation = el.getAnimations()[0]; const before = animation.currentTime; await new Promise(resolve => setTimeout(resolve, 200)); return getComputedStyle(el).animationPlayState === 'running' && animation.currentTime > before; }));
  record("creator SEO title", (await page.title()).includes("Websites for Creators"));
  record("canonical", await page.locator('link[rel="canonical"]').getAttribute("href") === "https://www.vigilstudios.co/creators");
  record("description/OG/Twitter", await page.locator('meta[name="description"]').count() === 1 && await page.locator('meta[property="og:image"]').count() > 0 && await page.locator('meta[name="twitter:card"]').getAttribute("content") === "summary_large_image");
  const ogURL = new URL(await page.locator('meta[property="og:image"]').getAttribute("content"));
  const image = await context.request.get(`${origin}${ogURL.pathname}${ogURL.search}`);
  const twitterURL = new URL(await page.locator('meta[name="twitter:image"]').getAttribute("content"));
  const twitterImage = await context.request.get(`${origin}${twitterURL.pathname}${twitterURL.search}`);
  record("Twitter image response", twitterImage.status() === 200 && twitterImage.headers()["content-type"].includes("image/png"));
  record("share image response", image.status() === 200 && image.headers()["content-type"].includes("image/png"));
  const imageBuffer = await image.body();
  record("share image is 1200×630 PNG", imageBuffer.readUInt32BE(16) === 1200 && imageBuffer.readUInt32BE(20) === 630);
  fs.writeFileSync(`${output}/creators-social.png`, imageBuffer);
  await page.setViewportSize({ width: 375, height: 812 });
  await page.goto(campaignUrl, { waitUntil: "domcontentloaded" });
  await page.getByRole("link", { name: "Start with Express", exact: true }).first().click();
  await page.waitForURL(/\/express\?/);
  record("Express entry preserves UTMs/ref", page.url().includes("utm_source=qa_creator") && page.url().includes("ref=creator-ref"));
  const buy = page.getByRole("link", { name: /^Buy/ });
  await buy.waitFor();
  const buyHref = await buy.getAttribute("href");
  record("Express Buy preserves template and campaign", buyHref.includes("template=restaurant") && buyHref.includes("vigil_campaign=creators") && buyHref.includes("utm_source=qa_creator"));
  await buy.click();
  await page.waitForURL(/\/checkout\?/);
  await page.getByRole("heading", { name: /website/ }).first().waitFor();
  availability.express = await page.getByRole("button", { name: "Continue to secure payment" }).count() === 1;
  if (availability.express) {
    record("Express reaches existing checkout", !await page.locator('text=Application error').count());
    const expressPrice = await page.locator("aside").innerText();
    record("Express checkout has real build price", expressPrice.includes("Vigil Express") && /\$[0-9]/.test(expressPrice));
  } else {
    record("Express online-unavailable state is explicit", await page.getByText("Online checkout is not switched on yet.", { exact: true }).isVisible());
    record("Express has working assisted-conversion email", await page.locator('a[href="mailto:hello@vigilstudios.co"]').isVisible());
  }
  await page.goto(campaignUrl, { waitUntil: "domcontentloaded" });
  await page.getByRole("link", { name: "Build with Professional", exact: true }).first().click();
  await page.waitForURL(/\/professional\?/);
  for (let i = 0; i < 3; i++) await page.getByRole("button", { name: "Continue", exact: true }).click();
  const professional = page.getByRole("link", { name: "Continue to checkout", exact: true });
  availability.professional = await professional.count() === 1;
  if (availability.professional) {
    await professional.waitFor();
    const professionalHref = await professional.getAttribute("href");
    record("Professional fit check retains build selector and attribution", professionalHref.includes("build=professional") && professionalHref.includes("utm_source=qa_creator"));
    await professional.click();
    await page.waitForURL(/\/checkout\?/);
    await page.getByRole("button", { name: "Continue to secure payment" }).waitFor();
    record("Professional reaches real checkout", (await page.locator("aside").innerText()).includes("Professional"));
    // Browser-only form event hook; prevent the server action so no order/payment is created.
    await page.locator('input[name="business_name"]').fill("Campaign QA");
    await page.locator('input[name="email"]').fill("campaign-qa@example.test");
    await page.locator('input[name="agree"]').check();
    await page.locator("form").evaluate(el => el.addEventListener("submit", event => event.preventDefault(), { once: true }));
    await page.getByRole("button", { name: "Continue to secure payment" }).click();
    record("checkout submission event carries package/UTMs", await page.evaluate(() => window.__campaignEvents.some(e => e.name === "creator_checkout_submitted" && e.data?.package === "professional" && e.data?.utm_source === "qa_creator")));
  } else {
    record("Professional online-unavailable state is explicit", await page.getByText(/Online Professional checkout is temporarily unavailable/).isVisible());
    const book = page.getByRole("button", { name: "Book a website call with us", exact: true });
    record("Professional provides its existing assisted booking route", await book.isVisible() && await book.isEnabled());
    await book.click();
    await page.getByRole("button", { name: "Close booking popup", exact: true }).waitFor();
    record("Professional assisted booking opens the real Calendly widget", await page.locator('iframe[src*="calendly.com"]').count() === 1);
    await page.getByRole("button", { name: "Close booking popup", exact: true }).click();
  }
  await page.goto(campaignUrl, { waitUntil: "domcontentloaded" });
  const focus = page.getByRole("link", { name: "Find your website", exact: true });
  await focus.focus();
  await page.keyboard.press("Tab"); await page.keyboard.press("Shift+Tab");
  record("keyboard-visible focus", await focus.evaluate(el => el.matches(":focus-visible") && parseFloat(getComputedStyle(el).outlineWidth) >= 2));
  await page.emulateMedia({ reducedMotion: "reduce" });
  record("reduced motion shows static reactions and hides animated cloud", await page.locator('[data-creator-static-reactions]').isVisible() && !await page.locator('[data-creator-reactions]').isVisible());
  record("reduced motion retains the usable hero CTA", await focus.isVisible());
  record('reduced motion stops collage and banner loops', await page.locator('[data-collage-float]').evaluateAll(els => els.every(el => getComputedStyle(el).animationName === 'none')) && !await page.locator('.creator-promo-track').isVisible() && await page.locator('.creator-promo-static').isVisible());
  record('reduced motion shows static project with no autoplay', !await page.locator('[data-creator-preview] video').isVisible() && !await page.locator('[data-creator-preview] button').isVisible());
  record("reduced motion removes CTA transitions", await focus.evaluate(el => getComputedStyle(el).transitionDuration === "0s"));
  await focus.press("Enter");
  await page.waitForURL(/#choose-your-site$/);
  record("keyboard campaign navigation", page.url().endsWith("#choose-your-site"));
  const noScript = await browser.newContext({ javaScriptEnabled: false, viewport: { width: 320, height: 812 } });
  const plain = await noScript.newPage(); await plain.goto(`${origin}/creators`, { waitUntil: "domcontentloaded" });
  record("server-rendered no-JS offers", await plain.getByRole("link", { name: "Build with Professional", exact: true }).count() === 2 && await plain.locator('a[href="/express"]').count() >= 2);
  await noScript.close();
  const retina = await browser.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 2 });
  const retinaPage = await retina.newPage();
  await retinaPage.goto(`${origin}/creators`, { waitUntil: 'domcontentloaded' });
  await retinaPage.locator('#creator-spotlight').evaluate(el => { const root = document.querySelector('#site-root'); root.scrollTop += el.getBoundingClientRect().top - 36; });
  await retinaPage.waitForFunction(() => { const video = document.querySelector('[data-creator-preview] video'); return video?.readyState >= 2 && video.currentTime > 0; });
  record('Retina spotlight video has enough native pixels for its rendered size', await retinaPage.locator('[data-creator-preview] video').evaluate(el => { const rect = el.getBoundingClientRect(); return el.videoWidth >= rect.width * devicePixelRatio && el.videoHeight >= rect.height * devicePixelRatio; }));
  record('Retina spotlight poster has enough native pixels for its rendered size', await retinaPage.locator('img[alt*="Scar"]').evaluate(el => el.naturalWidth >= el.getBoundingClientRect().width * devicePixelRatio));
  await retinaPage.waitForFunction(() => document.querySelector('[data-creator-preview] video').ended);
  await retinaPage.addStyleTag({ content: '.star-cursor-el { display:none!important; }' });
  await retinaPage.screenshot({ path: `${output}/creators-retina-spotlight.png` });
  await retina.close();
  const blocked = await browser.newContext();
  await blocked.addInitScript(() => { Object.defineProperty(window, "sessionStorage", { get() { throw new Error("Storage blocked"); } }); });
  const blockedPage = await blocked.newPage(); await blockedPage.goto(campaignUrl, { waitUntil: "domcontentloaded" });
  await blockedPage.getByRole("link", { name: "Build with Professional", exact: true }).first().click();
  await blockedPage.waitForURL(/\/professional/);
  record("storage blocked still routes with URL attribution", blockedPage.url().includes("utm_source=qa_creator"));
  await blocked.close();
  for (const event of ["creator_campaign_visit", "creator_express_cta_click", "creator_professional_cta_click", "creator_checkout_cta_click"]) {
    record(`${event}: event emitted`, events.some(item => item.name === event));
  }
  const touch = await browser.newContext({ viewport: { width: 320, height: 568 }, hasTouch: true, isMobile: true });
  const phone = await touch.newPage(); await phone.goto(campaignUrl, { waitUntil: "domcontentloaded" });
  await phone.screenshot({ path: `${output}/creators-touch-320-hero.png` });
  await phone.getByRole("link", { name: "Find your website", exact: true }).tap();
  await phone.waitForURL(/#choose-your-site$/);
  record("small iPhone touch: offer navigation", await phone.locator("#choose-your-site").evaluate(el => el.getBoundingClientRect().top < 220));
  record("small iPhone touch: no custom cursor", await phone.evaluate(() => !document.documentElement.classList.contains("star-cursor")));
  await phone.screenshot({ path: `${output}/creators-touch-320.png` });
  await touch.close();
  const standard = await browser.newContext();
  await standard.route("**/_vercel/insights/script.js*", route => route.fulfill({ status: 200, contentType: "text/javascript", body: "" }));
  await standard.addInitScript(() => { window.__events = []; window.va = (kind, value) => { if (kind === "event") window.__events.push(value); }; });
  const ordinary = await standard.newPage(); await ordinary.goto(`${origin}/express`, { waitUntil: "domcontentloaded" });
  const ordinaryBuy = ordinary.getByRole("link", { name: /^Buy/ });
  await ordinaryBuy.waitFor();
  record("ordinary Express visitor: original checkout selector", await ordinaryBuy.getAttribute("href") === "/checkout?template=restaurant");
  await ordinaryBuy.click(); await ordinary.waitForURL(/template=restaurant/);
  record("ordinary visitor: no creator attribution/events", !ordinary.url().includes("vigil_campaign") && await ordinary.evaluate(() => window.__events.length === 0));
  for (const route of ["/", "/pricing", "/express", "/professional", "/process", "/checkout?template=restaurant", "/login"]) {
    await ordinary.goto(`${origin}${route}`, { waitUntil: "domcontentloaded" });
    record(`${route}: public promotion banner present`, await ordinary.getByRole('complementary', { name: 'Creator promotion' }).count() === 1 && await ordinary.locator('.creator-promo-link').innerText().then(text => text.toLowerCase().includes('15% off')));
  }
  await ordinary.goto(`${origin}/?utm_source=ordinary_banner&utm_medium=site&utm_campaign=launch`, { waitUntil: 'domcontentloaded' });
  await ordinary.locator('.creator-promo-link').click();
  await ordinary.waitForURL(/\/creators.*#creator-hero$/);
  record('cross-page banner opens creator hero', await ordinary.locator('#site-root').evaluate(el => el.scrollTop <= 50));
  record("banner activates campaign only on click and retains source", await ordinary.evaluate(() => window.__events.some(e => e.name === 'creator_promotion_banner_click' && e.data?.utm_source === 'ordinary_banner')));
  await ordinary.getByRole('link', { name: 'Start with Express', exact: true }).first().click();
  await ordinary.waitForURL(/\/express\?/);
  record("banner visitor attribution persists downstream", ordinary.url().includes('utm_source=ordinary_banner') && ordinary.url().includes('vigil_campaign=creators'));
  await standard.close();
  record("no hydration/runtime errors", errors.length === 0, errors);
} finally {
  fs.writeFileSync(`${output}/browser-results.json`, JSON.stringify({ results, errors, availability }, null, 2));
  console.log(JSON.stringify({ passed: results.filter(r => r.pass).length, failed: results.filter(r => !r.pass), errors, availability }, null, 2));
  await browser.close();
}
