import type { TypographyProfileId } from "../../foundations/typography/profiles";
import type { ArtDirectionId } from "../../foundations/art-direction";
export type HeroConcept = {
  id: string; name: string; typography: TypographyProfileId; art: ArtDirectionId;
  palette: [string,string,string];
  thesis: string; mechanism: string; predictable: string; motion: string; mobile: string;
  industries: [string,string,string];
  axes: [string,string,string,string,string,string];
};
/** Concept review data only. Deliberately absent from the component registry. */
export const batch003: readonly HeroConcept[] = [
  { id:"H17",name:"The Front Page",typography:"editorial",art:"publication",palette:["#f1ecdf","#252a25","#853523"],thesis:"A cover story gives the brand an editorial point of view.",mechanism:"An oversized publication masthead anchors an unequal story spread; headline, scene and marginal abstract form one reading path.",predictable:"A large serif headline above a centered image. Replace it with a masthead and a real story hierarchy.",motion:"Still first frame; one optional image wipe on entry. No word stagger.",mobile:"Masthead, headline, image, abstract; side folio becomes a byline.",industries:["Architecture journal: place story","Food producer: harvest edition","Research organization: field report"],axes:["serif-contrast","masthead-spread","landscape-band","reading","still","editorial-medium"] },
  { id:"H18",name:"Open Circuit",typography:"technical",art:"precision",palette:["#071f27","#d9f1ed","#b7f568"],thesis:"Show the system working before describing it.",mechanism:"A single legible signal plot is the visual anchor; a readout and proposition share the plot's baseline. Data must be real or explicitly illustrative.",predictable:"SaaS dashboard cards and decorative grids. Use one meaningful signal and a clear claim instead.",motion:"User-selectable time window in a later prototype; no fake live feed. Static chart in this study.",mobile:"Headline then signal, with readout underneath. Do not squeeze axis labels.",industries:["Energy: output signal","Audio studio: frequency response","Logistics: route continuity"],axes:["mono","signal-baseline","data-vector","time-window","state-change","dense-precise"] },
  { id:"H19",name:"The Bill",typography:"poster",art:"billboard",palette:["#e84c25","#24170f","#24170f"],thesis:"An event identity with the urgency of a physical bill.",mechanism:"A vertical date ticket interrupts a stacked title; the action sits on a full-width program strip. The date is content, not decoration.",predictable:"Big text over a concert photograph. Build a type-led event bill with ticket and running order.",motion:"Short vertical program-strip reveal; display text stays still. Study is static.",mobile:"Title and date remain side-by-side; program strip wraps into a list.",industries:["Music venue: season opening","Museum: late exhibition","Fitness: regional competition"],axes:["condensed-caps","ticket-poster","type-only","booking","strip-reveal","dense-graphic"] },
  { id:"H20",name:"A Place at the Table",typography:"humanist",art:"salon",palette:["#f2dfbe","#344935","#344935"],thesis:"An invitation shaped around a person's reason for visiting.",mechanism:"A friendly question opens into a broad subject image, with a conversational route sentence below. Choices have useful destinations rather than becoming cards.",predictable:"Wellness headline with three floating cards. Use one invitation and an image that establishes belonging.",motion:"No entrance motion; later route selection may update the contextual sentence.",mobile:"Question, broad image, route sentence. Choice links wrap with generous touch spacing.",industries:["Community venue: gather or learn","Hospitality: stay or dine","Furniture: home or workspace"],axes:["humanist","invitation-bowl","broad-object","route-choice","none","open-warm"] },
  { id:"H21",name:"Index / Now",typography:"neo-grotesk",art:"precision",palette:["#e6e8e4","#181b1c","#25523a"],thesis:"A practice defined by what it is doing now.",mechanism:"The proposition is part of a large live-work index; one open row becomes a panorama, with the next row visible as continuation.",predictable:"Portfolio thumbnails in a grid. Make the selected project occupy the row's entire visual field.",motion:"A later keyboard-operable disclosure resizes only the selected row; no hover-only imagery.",mobile:"Keep the thesis first; stack rows and let selected media expand vertically.",industries:["Architecture: current civic work","Film company: current releases","Environmental group: active sites"],axes:["heavy-sans","expanding-index","panorama-row","disclosure","height-transition","dense-systematic"] },
  { id:"H22",name:"Between Acts",typography:"fashion",art:"runway",palette:["#eee8e6","#4d2330","#4d2330"],thesis:"The pause between images becomes an expressive part of the identity.",mechanism:"Two oversized italic phrases bookend a low photographic ribbon; a small side caption creates an intentional interruption in the reading rhythm.",predictable:"Fashion split screen with a portrait. Use a horizontal interval and typography that passes through the scene's edges.",motion:"Slow horizontal media reveal only; no perpetual parallax or animated type.",mobile:"Phrases become top and bottom bookends around a taller image ribbon.",industries:["Dance company: seasonal program","Fashion atelier: new collection","Ceramic studio: firing story"],axes:["italic-serif","typographic-bookends","film-ribbon","linear-reading","horizontal-wipe","extreme-pause"] },
  { id:"H23",name:"Edition One",typography:"luxury",art:"gallery",palette:["#242b35","#f0e4cf","#e4b88a"],thesis:"An edition has provenance before it has a sales pitch.",mechanism:"An oversized edition numeral and a narrow product portrait create a single central lockup; a precise caption and quiet side proposition complete it.",predictable:"Luxury object centered above a button. Give the edition and its material history equal visual weight.",motion:"Optional brief dissolve of the product view, triggered by intent; no automatic rotation.",mobile:"Edition and image share one row; proposition and provenance follow.",industries:["Furniture: numbered edition","Winemaker: vintage release","Publisher: artist monograph"],axes:["fine-serif","edition-lockup","portrait-object","inspect","dissolve","sparse-formal"] },
  { id:"H24",name:"Made to Measure",typography:"brutalist",art:"billboard",palette:["#efe948","#23231c","#23231c"],thesis:"Make the product's construction legible.",mechanism:"A blunt stacked promise faces an exploded assembly diagram; a specification band sits at the joint between title and drawing. No generic capability cards.",predictable:"Brutalist all-caps slogan with random shapes. Tie every plane to a real configurable part.",motion:"Later part selection aligns one diagram plane with its specification. Static exploded state here.",mobile:"Headline then assembly drawing; specifications become a plain semantic list.",industries:["Furniture: modular shelving","Building systems: panel assembly","Audio: modular hardware"],axes:["black-sans","assembly-joint","exploded-vector","part-selection","snap-align","dense-industrial"] },
  { id:"H25",name:"Three Ways In",typography:"geometric",art:"publication",palette:["#dfe8f3","#263f6b","#263f6b"],thesis:"Orientation can be the first act of hospitality.",mechanism:"Three typographic routes branch from one entry point across an open field. Destinations are the architecture, not decorative lines behind a headline.",predictable:"Three centered service cards. Use a clear route diagram with distinct destinations and one brand proposition.",motion:"Focus illuminates a route in a future prototype; never an auto-drawing background grid.",mobile:"Branch becomes a vertical path with three full-width destinations.",industries:["Cultural campus: learn / see / meet","Travel group: coast / hills / city","Education: study / research / visit"],axes:["geometric","branching-route","wayfinding-vector","destination-navigation","focus-highlight","balanced-spatial"] },
  { id:"H26",name:"Good Company",typography:"playful",art:"salon",palette:["#f8c8ac","#622828","#622828"],thesis:"Personality comes from the invitation and type, not ornamental blobs.",mechanism:"A compact conversational preface leads to a huge two-line promise. The final word is a visibly selected alternative; a broad reply line gives the visitor a next step.",predictable:"Bouncy headline, gradient shapes and pill cards. Build a language-led invitation with one explicit choice.",motion:"Later choice changes one word and the action destination. No animated variable axes while reading.",mobile:"Keep complete sentence order; selected word fits on its own line and alternatives become text links.",industries:["Repair collective: mend / reuse","Community kitchen: cook / share","Learning studio: make / discover"],axes:["casual-variable","sentence-choice","text-only","word-selection","word-replace","open-expressive"] },
  { id:"H27",name:"The Evidence Margin",typography:"editorial",art:"precision",palette:["#ecece4","#233b35","#233b35"],thesis:"The brand's point of view meets one piece of tangible evidence.",mechanism:"A short editorial thesis occupies one continuous reading column; a full-height marginal strip pairs source, detail image and outcome. It is one argument, not a statistics grid.",predictable:"Testimonial quote card beside three metrics. Make evidence a margin bound to the main proposition.",motion:"No reveal required; optional source-note disclosure in a later prototype.",mobile:"Thesis, detail image, then clearly attributed source and outcome; retain the reading order.",industries:["Conservation: material restoration","Legal practice: anonymized case insight","Engineering: tested construction detail"],axes:["serif-contrast","evidence-margin","macro-document","source-disclosure","none","reading-dense"] },
  { id:"H28",name:"After Hours",typography:"poster",art:"runway",palette:["#111516","#f1eee4","#dab46d"],thesis:"The image holds the opening silence; the title arrives at the floor.",mechanism:"An almost uncaptioned stage image dominates the upper field; a monumental condensed title anchors the bottom edge with the event information in a narrow vertical gutter.",predictable:"Centered cinematic slogan over a dark photo. Keep the scene open and place the title below its focal subject.",motion:"A short exposure wipe on the image; title remains present from first paint.",mobile:"Scene first, title beneath it, event gutter becomes a single line above the action.",industries:["Performance venue: evening series","Hospitality: supper club","Photography: nocturnal exhibition"],axes:["condensed-caps","floor-title","open-scene","event-details","exposure-wipe","cinematic-open"] },
];
