"use client";
import { useState, type ReactNode } from "react";
import { DesignThemeProvider } from "../../foundations/DesignThemeProvider";
import { LabEditor } from "../editor/LabEditor";
import { collection005Review } from "./review";
import { mediaBriefs, briefForStudy } from "./fixtures";
import { mediaStudies, studyContract, type MediaStudy } from "./studies";
import { MediaStudyArtwork } from "./Study";

export function MediaCollectionGallery({ toolbar, workspaceSwitch }: { toolbar?:ReactNode;workspaceSwitch?:ReactNode }) {
  const [selected,setSelected]=useState("M13"),[adaptation,setAdaptation]=useState(3),[device,setDevice]=useState("desktop"),[overview,setOverview]=useState(false),[tab,setTab]=useState("study");
  const study=mediaStudies.find(s=>s.id===selected)!;
  const brief=mediaBriefs[adaptation];
  const render=(s:MediaStudy)=>{ const palette=s.id === "M05" ? [["#211920","#f2eee5","#dbbc79"],["#111e29","#e3edf2","#9bc9d8"],["#2b191d","#f2dca8","#f2c795"],["#171b18","#eeefe8","#bfda78"]][adaptation] : brief.palette; return <DesignThemeProvider key={`${s.id}-${brief.id}`} typography={s.typography[adaptation]} artDirection={s.art} motion="none" overrides={{color:{background:palette[0],surface:palette[0],surfaceElevated:palette[0],foreground:palette[1],muted:palette[1],accent:palette[2],accentForeground:palette[0],border:palette[1]}}}><MediaStudyArtwork study={s} brief={briefForStudy(s.id,brief)} viewportHeight={device === "mobile" ? 844 : device === "tablet" ? 1024 : 900}/></DesignThemeProvider>; };
  return <LabEditor title="Design Lab" toolbar={toolbar} workspaceSwitch={workspaceSwitch} canvasWidth={overview?1440:device==="mobile"?390:device==="tablet"?768:1440} resetKey={`${selected}-${adaptation}-${overview}-${device}`} activeTab={tab} onTabChange={setTab} tabs={[
    {id:"study",label:"Study",content:<><header className="calibration-intro"><h2>Collection 005 · Media / Work</h2><p>Thirteen creative studies. Twelve visually accepted; M03 needs revision; M13 is explicitly approved. These original studies remain separate from reusable implementations in the Component catalog.</p></header><div className="calibration-controls"><label>Media study<select aria-label="Media study" value={selected} disabled={overview} onChange={e=>setSelected(e.target.value)}>{mediaStudies.map(s=><option key={s.id} value={s.id}>{s.id} · {s.name}</option>)}</select></label><label>Client adaptation<select aria-label="Media client adaptation" value={adaptation} onChange={e=>setAdaptation(Number(e.target.value))}>{mediaBriefs.map((b,i)=><option key={b.id} value={i}>{b.brand} · {b.context}</option>)}</select></label><label>Client artboard<select aria-label="Media client artboard" value={device} disabled={overview} onChange={e=>setDevice(e.target.value)}><option value="desktop">Desktop · 1440px</option><option value="tablet">Tablet · 768px</option><option value="mobile">Mobile · 390px</option></select></label><button type="button" aria-pressed={overview} onClick={()=>setOverview(v=>!v)}>{overview?"Return to selected study":"Compare thirteen studies"}</button></div><div className="m5-notes"><p><strong>{collection005Review[study.id].status}</strong> · {collection005Review[study.id].note}</p><p><strong>{study.family}</strong> · {study.scope}</p><p>{study.dna}</p><p>{study.typography[adaptation]} / {study.art}. Authored layers; motion none. Interactions work directly on the artboard.</p><p>{study.interaction}</p></div></>},
    {id:"contract",label:"Contract",content:<div className="m5-notes"><h2>{study.id} · {study.name}</h2><dl>{[["Category / scope",`portfolio · ${study.family} · ${study.scope}`],["Content",study.content],["Media",study.media],["Count / ratios",`${study.count.join("–")} records. ${study.ratios}`],["Type / art compatibility",`${study.typography.join(" / ")} · ${study.art}. Other local overrides unsupported.`],["Section controls",study.controls.join("; ")],["Mobile",study.mobile],["Constraints",study.constraints],["Proposed motion",study.motion]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p>Proposal contract uses existing engine vocabulary. These schemas are not registered in Composition; human selection precedes strict reusable implementation.</p><details><summary>Composition handoff contract</summary><pre style={{whiteSpace:"pre-wrap",fontSize:".7rem"}}>{JSON.stringify(studyContract(study),null,2)}</pre></details></div>},
    {id:"review",label:"Review",content:<div className="m5-notes"><h2>Creative review / human feedback</h2><p>3 Portfolio · 5 Gallery · 3 Campaign · 2 Mixed media. M01–M12 received positive visual feedback except M03, whose connectors need real meaning. M13 is the requested additional viewport gallery, explicitly approved and registered in Composition Lab. The original twelve-study diversity dossier remains historical.</p><h3>Experimental shortlist</h3><p><strong>M01 Open index:</strong> compact project directory with accessible progressive disclosure. Medium complexity; full case studies are outside its record schema.</p><p><strong>M04 Contact room:</strong> proofing and selective inspection across mixed ratios. Medium complexity; larger archives need pagination and thumbnail delivery.</p><p><strong>M08 Campaign folio:</strong> an editorial spread that changes composition on mobile. Medium complexity; requires concise copy and intentional pairs.</p><p><strong>M11 Media cabinet:</strong> heterogeneous still/video archive with subject filtering. High complexity; production needs caption tracks, pagination and source optimization.</p><p><strong>M12 Light table:</strong> independent comparisons without image registration. Medium complexity; no synchronized video or persistent annotations.</p><p>The shortlist above predates the current human review. Visual acceptance does not imply production readiness. Reusable implementations follow the separate registry evidence gate. These studies retain their human dispositions; no commerce or next collection is implemented.</p><h3>Provenance / limitations</h3><p>Urban apparel uses four AI-generated illustrative campaign photographs. Other adaptations use existing local study imagery plus photo assets extracted from the existing Express retail/restaurant HTML. No layout or source code was imported from Express. Silent reels are edits of these stills, not original motion footage. Fictional brands and copy; no client claims.</p><p>Full-page-capable means a scalable section inside a host page; page routing, navigation and recipes remain the host’s responsibility.</p></div>},
  ]}>{overview?<div className="m5-overview">{mediaStudies.map(s=><article key={s.id}><h3>{s.id} · {s.name} / {s.family}</h3><div className="m5-overview-stage" inert>{render(s)}</div><button type="button" onClick={()=>{setSelected(s.id);setOverview(false);}}>Inspect {s.id} · {s.name} ↗</button></article>)}</div>:render(study)}</LabEditor>;
}
