"use client";
/* Native images are intentional in portable, contained creative studies. */
/* eslint-disable @next/next/no-img-element */
import { ViewportGallery } from "./ViewportGallery";
import { useId, useRef, useState } from "react";
import type { MediaBrief, MediaItem } from "./fixtures";
import { type MediaStudy, validateStudyBrief } from "./studies";

function Plate({ item, className = "", eager = false }: { item: MediaItem; className?: string; eager?: boolean }) {
  return <img className={`m5-image ${className}`} src={item.src} alt={item.alt} data-orientation={item.height > item.width ? "portrait" : "landscape"} width={item.width} height={item.height} loading={eager ? "eager" : "lazy"} decoding="async" style={{ objectPosition: `${item.focal[0]}% ${item.focal[1]}%` }} />;
}
const number = (i: number) => String(i + 1).padStart(2, "0");
function Caption({ item, index }: { item: MediaItem; index: number }) { return <figcaption><span className="de-mono">{number(index)} / {item.group}</span><h3 className="de-heading">{item.title}</h3><p className="de-text">{item.note}</p></figcaption>; }

/** Lab-only prototypes. No registry promotion, global controls or client-site dependencies. */
export function MediaStudyArtwork({ study: s, brief: b, viewportHeight }: { study: MediaStudy; brief: MediaBrief; viewportHeight?: number }) {
  const [active, setActive] = useState(0), [filter, setFilter] = useState("All"), [well, setWell] = useState(0), [pins, setPins] = useState([0,1]);
  const rail = useRef<HTMLDivElement>(null);
  const uid = useId();
  const errors = validateStudyBrief(s,b);
  if(errors.length) return <section className="m5-invalid" role="alert"><h2>Unsupported study content</h2>{errors.map(e=><p key={e}>{e}</p>)}</section>;
  if (s.id === "M13") return <ViewportGallery brief={b} viewportHeight={viewportHeight}/>;
  const items = b.items, current = items[Math.min(active,items.length-1)];
  const pairCount = Math.ceil(items.length/2), pair = Math.min(active,pairCount-1)*2;
  const paginate = (count: number, label: string) => <div className="m5-pagination" aria-label={label}><button type="button" disabled={active===0} onClick={()=>setActive(i=>Math.max(0,i-1))} aria-label={`Previous ${label}`}>← <span>Previous</span></button><span className="de-mono" role="status">{number(active)} / {String(count).padStart(2,"0")}</span><button type="button" disabled={active>=count-1} onClick={()=>setActive(i=>Math.min(count-1,i+1))} aria-label={`Next ${label}`}><span>Next</span> →</button></div>;
  const frameButtons = (className="") => <div className={`m5-selectors ${className}`}>{items.map((item,i)=><button key={item.id} type="button" aria-pressed={active===i} aria-label={`View ${number(i)}: ${item.title}`} onClick={()=>setActive(i)}><Plate item={item}/><span className="de-mono">{number(i)}</span></button>)}</div>;
  const heading = <header className="m5-title"><p className="de-accent">{b.season}</p><h2 id={`${uid}-title`} className="de-display">{b.title}</h2><p className="de-text">{b.deck}</p></header>;
  return <section className={`media-study media-study--${s.id}`} aria-labelledby={`${uid}-title`} data-study={s.id} data-brief={b.id}>
    <div className="m5-folio"><span className="de-accent">{b.brand}</span><span className="de-mono">{s.family} / {s.id}</span></div>
    {heading}
    {s.id==="M01" ? <div className="m5-index">{items.map((item,i)=><details key={item.id} open={i===0}><summary><span className="de-mono">{number(i)}</span><h3 className="de-heading">{item.title}</h3><span className="de-accent">{item.group}</span><span className="m5-index-sign" aria-hidden="true">↗</span></summary><div className="m5-index-record"><Plate item={item} eager={i===0}/><div><p className="de-mono">Project note / {number(i)}</p><p className="de-text">{item.note}</p><p className="de-accent">{b.context}</p></div></div></details>)}</div> : null}
    {s.id==="M02" ? <div className="m5-chapters">{items.map((item,i)=><article key={item.id}><header><span className="de-display">{number(i)}</span><h3 className="de-heading">{item.title}</h3></header><Plate item={item} eager={i===0}/><div className="m5-chapter-foot"><p className="de-text">{item.note}</p><figure><Plate item={items[(i+1)%items.length]}/><figcaption className="de-mono">Next reading / {items[(i+1)%items.length].title}</figcaption></figure></div></article>)}</div> : null}
    {s.id==="M03" ? <div className="m5-atlas"><svg viewBox="0 0 1000 650" preserveAspectRatio="none" aria-hidden="true"><path d="M100 110 L500 330 L850 110 M140 540 L500 330 L850 530 M500 20 L500 330 L500 620"/></svg><div className="m5-atlas-stations">{items.map((item,i)=><button type="button" key={item.id} className={`m5-station m5-station-${i}`} aria-pressed={active===i} onClick={()=>setActive(i)}><span className="de-mono">{number(i)} / {item.group}</span><strong className="de-accent">{item.title}</strong></button>)}</div><figure className="m5-atlas-main"><Plate item={current} eager/><figcaption role="status"><span className="de-mono">Selected project / {number(active)}</span><h3 className="de-heading">{current.title}</h3><p className="de-text">{current.note}</p></figcaption></figure></div> : null}
    {s.id==="M04" ? <div className="m5-contact"><figure className="m5-contact-selected" aria-live="polite"><Plate item={current} eager/><Caption item={current} index={active}/></figure><div className="m5-proof"><p className="de-mono">Proof sheet / select an exposure</p>{frameButtons()}<p className="de-text">A sequence of observations.<br/>Keep looking.</p></div></div> : null}
    {s.id==="M05" ? <div className="m5-screening"><figure aria-live="polite"><Plate item={current} eager/><Caption item={current} index={active}/></figure>{paginate(items.length,"frame")}</div> : null}
    {s.id==="M06" ? <><div className="m5-walk-note"><span className="de-accent">A walk through the work →</span><p className="de-text">Move at your own pace. Each scene keeps its own horizon.</p></div><div ref={rail} className="m5-walk" role="region" aria-label="Photographic promenade" tabIndex={0}>{items.map((item,i)=><figure key={item.id} tabIndex={-1} data-scene={i}><Plate item={item} eager={i===0}/><Caption item={item} index={i}/></figure>)}</div><div className="m5-pagination">{[-1,1].map(delta=><button key={delta} type="button" onClick={()=>{const children=rail.current?.children;if(!children||!rail.current)return;const x=rail.current.scrollLeft;const index=Array.from(children).reduce((best,el,i)=>Math.abs((el as HTMLElement).offsetLeft-x)<Math.abs((children[best] as HTMLElement).offsetLeft-x)?i:best,0);const next=Math.max(0,Math.min(items.length-1,index+delta));const target=children[next] as HTMLElement;rail.current.scrollTo({left:target.offsetLeft,behavior:"instant"});target.focus({preventScroll:true});}}>{delta===-1?"← Previous scene":"Next scene →"}</button>)}</div></> : null}
    {s.id==="M07" ? <div className="m5-hanging">{items.map((item,i)=><figure key={item.id}><Plate item={item} eager={i===0}/><Caption item={item} index={i}/></figure>)}</div> : null}
    {s.id==="M08" ? <><div className="m5-book"><figure className="m5-book-left"><Plate item={items[pair]} eager/><figcaption className="de-mono">{number(pair)} / {items[pair].title}</figcaption></figure><div className="m5-book-right"><span className="de-accent">{b.season}</span><h3 className="de-display">{items[pair].title}</h3><p className="de-text">{items[pair].note}</p>{items[pair+1] ? <figure><Plate item={items[pair+1]}/><figcaption className="de-mono">{number(pair+1)} / {items[pair+1].title}</figcaption></figure>:<p className="de-accent">End of this edition.</p>}</div></div>{paginate(pairCount,"spread")}</> : null}
    {s.id==="M09" ? <><div className="m5-look"><figure className="m5-look-main"><Plate item={items[pair]} eager/><Caption item={items[pair]} index={pair}/></figure><div className="m5-look-side"><p className="de-display">{number(active)}</p><span className="de-accent">A closer conversation</span><figure><Plate item={items[pair+1]}/><Caption item={items[pair+1]} index={pair+1}/></figure></div></div><div className="m5-pairs" aria-label="Authored image pairs">{Array.from({length:pairCount},(_,i)=><button type="button" key={i} aria-pressed={active===i} onClick={()=>setActive(i)}>Pair {number(i)} / {items[i*2].title}</button>)}</div><p className="de-mono" role="status">Selected pair {number(active)}: {items[pair].title} + {items[pair+1].title}</p></> : null}
    {s.id==="M10" ? <div className="m5-score">{items.map((item,i)=><article key={item.id}><h3 className="de-display">{item.title}</h3><div className="m5-score-band"><Plate item={item} eager={i===0}/><span className="de-mono">{number(i)} / {b.brand}</span></div><div className="m5-score-foot"><p className="de-text">{item.note}</p><figure><Plate item={item}/><figcaption className="de-mono">The complete frame</figcaption></figure></div></article>)}</div> : null}
    {s.id==="M11" ? <><div className="m5-filters" aria-label="Filter media by subject">{["All",...new Set(items.map(i=>i.group))].map(group=><button type="button" key={group} aria-pressed={filter===group} onClick={()=>setFilter(group)}>{group}</button>)}</div><p role="status" className="de-mono">{items.filter(i=>filter==="All"||i.group===filter).length} records / {filter}</p><div className="m5-cabinet">{items.filter(i=>filter==="All"||i.group===filter).map(item=><article key={item.id} data-kind={item.kind}><header><span className="de-display">{number(items.indexOf(item))}</span><span className="de-mono">{item.kind==="video"?"MOTION / SILENT REEL":"STILL / IMAGE"}</span></header>{item.kind==="video"?<video controls playsInline preload="none" poster={item.poster} aria-label={item.title} src={item.src}/>:<Plate item={item}/>}<h3 className="de-heading">{item.title}</h3><p className="de-text">{item.note}</p>{item.transcript?<details><summary>Visual transcript</summary><p className="de-text">{item.transcript}</p></details>:null}</article>)}</div></> : null}
    {s.id==="M12" ? <><div className="m5-wells">{pins.map((pin,i)=><div key={i}><button type="button" aria-pressed={well===i} onClick={()=>setWell(i)} className="m5-well-button">{i===0?"A / Left well":"B / Right well"} {well===i?"— selecting":"— select"}</button><figure><Plate item={items[pin]} eager/><Caption item={items[pin]} index={pin}/></figure></div>)}</div><p className="de-text" role="status">Choose an image for the {well===0?"left":"right"} well. Left: {items[pins[0]].title}. Right: {items[pins[1]].title}.</p><div className="m5-tray" aria-label="Media source tray">{items.map((item,i)=><button type="button" key={item.id} aria-label={`Place ${item.title} in ${well===0?"left":"right"} well`} aria-pressed={pins[well]===i} onClick={()=>setPins(p=>p.map((value,index)=>index===well?i:value))}><Plate item={item}/><span className="de-mono">{number(i)} / {item.title}</span></button>)}</div></> : null}
    <footer className="m5-end"><span className="de-accent">{b.brand}</span><span className="de-mono">{b.context} · Illustrative creative study</span></footer>
  </section>;
}
