import type { ArtDirectionId } from "../../foundations/art-direction";
import type { TypographyProfileId } from "../../foundations/typography/profiles";
import type { SectionContract } from "../../composition/contracts";
import type { MediaBrief } from "./fixtures";
export type MediaStudy = {
  id: string; name: string; family: "Portfolio / Work" | "Gallery / Photography" | "Lookbook / Campaign" | "Mixed Media";
  scope: "both" | "page-capable" | "section-oriented"; typography: readonly [TypographyProfileId,TypographyProfileId,TypographyProfileId,TypographyProfileId]; art: ArtDirectionId;
  dna: string; count: readonly [number,number]; ratios: string; content: string; media: string; mobile: string; interaction: string; motion: string; constraints: string; controls: readonly string[];
};
export const mediaStudies: readonly MediaStudy[] = [
  {id:"M01",name:"Open index",family:"Portfolio / Work",scope:"both",typography:["neo-grotesk","technical","humanist","neo-grotesk"],art:"precision",dna:"A typographic project directory opens in place into a large image and a working note. The index remains the navigation.",count:[3,12],ratios:"Portrait, square, landscape; contained in expanded stage",content:"Project title, discipline, short summary and cover per entry.",media:"One cover per project; 3–12 independent projects.",mobile:"Rows retain title and discipline; an opened record becomes image then note. No hover preview or sideways table.",interaction:"Native independent disclosures. Enter/Space opens a project without leaving its place in the index.",motion:"Proposed: height-aware disclosure reveal; preserve instant native opening under reduced motion.",constraints:"No nested project navigation yet. A project is one record, not a full case-study schema.",controls:["Expanded projects","Client adaptation","Artboard"]},
  {id:"M02",name:"Project chapters",family:"Portfolio / Work",scope:"page-capable",typography:["editorial","geometric","luxury","neo-grotesk"],art:"publication",dna:"A numbered project unfolds through large landscape chapter scenes; an inset evidence image and marginal notes interrupt each chapter.",count:[3,8],ratios:"Landscape scenes with optional portrait details",content:"Ordered chapter title, summary and contextual image.",media:"3–8 sequential scenes; next image doubles as a clearly labeled detail preview.",mobile:"Chapter number precedes image. Detail and note share a compact two-column foot, preserving a different pace from vertical cards.",interaction:"Continuous native document reading; no scroll pinning.",motion:"Proposed: chapter threshold reveal and very shallow image parallax; static images are the baseline.",constraints:"Sequence must tell one project narrative. Panoramic crop requires a safe subject area.",controls:["Client adaptation","Artboard"]},
  {id:"M03",name:"Project constellation",family:"Portfolio / Work",scope:"both",typography:["geometric","neo-grotesk","playful","technical"],art:"gallery",dna:"A selected project occupies a central viewing field; a connected ring of named project selectors behaves as a spatial directory.",count:[3,6],ratios:"Any source ratio; central image is contained",content:"3–6 short project names, categories, one sentence each.",media:"One independent project cover per station.",mobile:"The spatial ring becomes a numbered button band above the image, retaining project selection without miniature labels or dragging.",interaction:"Named buttons select the central project; pressed state and live caption expose selection.",motion:"Proposed: connector emphasis on selection, with no orbiting or automatic movement.",constraints:"Bounded to six stations. The arrangement conveys navigation, not geography or a measured relationship.",controls:["Selected project","Client adaptation","Artboard"]},
  {id:"M04",name:"Contact room",family:"Gallery / Photography",scope:"both",typography:["technical","brutalist","neo-grotesk","technical"],art:"precision",dna:"An inspectable proof sheet puts numbered small exposures beside one enlarged selection and its notebook caption.",count:[4,24],ratios:"Mixed ratios preserved in proof frames",content:"Frame number, image title and short photographer note.",media:"4–24 still photographs. Sheet thumbnails use contain; no important detail is cropped.",mobile:"Enlargement comes first, followed by a four-column contact sheet. Tap targets remain 44px or larger.",interaction:"Every frame button selects the enlargement; current selection is visible and announced.",motion:"Proposed: instant-to-crossfade enlargement; no automatic slideshow.",constraints:"Bounded study sheet; larger archives need pagination and thumbnail delivery before production.",controls:["Selected frame","Client adaptation","Artboard"]},
  {id:"M05",name:"The screening room",family:"Gallery / Photography",scope:"both",typography:["luxury","humanist","editorial","poster"],art:"gallery",dna:"One photograph fills a dark viewing room with a contained image, a generous title outside the photograph, and deliberate previous/next pacing.",count:[3,30],ratios:"All ratios contained in a stable 16:10 stage",content:"Series title, image title and contextual caption.",media:"3–30 photographs; only the active image is mounted.",mobile:"A shorter 4:5 viewing stage contains the whole image; controls sit below it. Buttons supplement native touch taps; no swipe-only action.",interaction:"Previous/next buttons with bounded ends and live frame count. No autoplay.",motion:"Proposed: cinematic crossfade after explicit navigation; instant switch under reduced motion.",constraints:"Dark room is structural; arbitrary bright palette override is not exposed. Image caption remains outside the image.",controls:["Previous / next frame","Client adaptation","Artboard"]},
  {id:"M06",name:"Horizon walk",family:"Gallery / Photography",scope:"page-capable",typography:["humanist","geometric","technical","neo-grotesk"],art:"publication",dna:"A horizontal photographic promenade alternates long landscape vistas with narrow portrait pauses, captioned on a continuous baseline.",count:[3,12],ratios:"Natural landscape and portrait, no uniform card crop",content:"Ordered scenes and a short walk note for each.",media:"3–12 images with dimensions; natural ratios determine the width of each scene.",mobile:"Native horizontal overflow keeps a visible next-scene edge. Images shrink to 58cqw height, captions stay with their scenes. Touch pan and keyboard buttons coexist.",interaction:"Native horizontal scrolling plus previous/next scene buttons that focus the destination caption.",motion:"Proposed: optional restrained smooth progression; no vertical-scroll hijacking.",constraints:"Not an infinite rail. No sticky spacer, wheel interception or auto-pan. Full-page use needs a host title/navigation.",controls:["Previous / next scene","Client adaptation","Artboard"]},
  {id:"M07",name:"Salon hanging",family:"Gallery / Photography",scope:"both",typography:["fashion","luxury","editorial","neo-grotesk"],art:"runway",dna:"An asymmetric hanging of whole images uses changing size and offset to create a wall with intentional pauses; titles sit like gallery labels.",count:[4,12],ratios:"Original aspect ratios, uncropped",content:"Work title, medium or context, optional short note.",media:"4–12 still works with reliable dimensions; supports highly inconsistent aspect ratios.",mobile:"A two-track hanging preserves unequal scale and offset, then widens every third image. Reading order remains row-major.",interaction:"Static visual browsing; images are not pretend buttons.",motion:"Proposed: individual reveal on entering view; all works visible with motion none.",constraints:"No CSS masonry that changes reading order. Very wide panoramas need their own wider slot.",controls:["Client adaptation","Artboard"]},
  {id:"M08",name:"Campaign folio",family:"Lookbook / Campaign",scope:"both",typography:["fashion","editorial","luxury","brutalist"],art:"publication",dna:"A paged editorial spread binds a portrait plate to an opposite image-and-essay page, with a visible spine and running folio.",count:[4,12],ratios:"Portrait principal plate; mixed secondary images",content:"Campaign heading, spread titles, one editorial sentence per plate.",media:"Even pairs preferred; odd final image becomes a single plate without duplication.",mobile:"A spread compresses into a portrait plate with its facing-page inset and note beneath; explicit spread controls remain together.",interaction:"Previous/next spread buttons; no page-flip library or gesture requirement.",motion:"Proposed: restrained spread dissolve, not simulated 3D paper.",constraints:"Keep prose concise. No shopping data or price fields; images imply editorial relationships only.",controls:["Previous / next spread","Client adaptation","Artboard"]},
  {id:"M09",name:"Look / closer",family:"Lookbook / Campaign",scope:"section-oriented",typography:["neo-grotesk","technical","geometric","neo-grotesk"],art:"precision",dna:"A dominant full-look image sits beside a smaller uncropped companion plate and a large numbered selector. Each selection is an authored image pair.",count:[4,12],ratios:"Portrait or landscape overview with any-ratio companion",content:"Look title, overview note and companion note.",media:"2–6 explicit pairs. Companion may show material, context or a second view; never implies optical magnification.",mobile:"Overview and companion stay side by side at unequal widths; prose drops below. Pair selector is a wrapping button row.",interaction:"Numbered buttons switch both paired images and both captions together.",motion:"Proposed: paired-image reveal on selection. No magnifier or fake product zoom.",constraints:"Requires even image count and authored pairing. It is visual presentation, with no variant, stock or cart model.",controls:["Selected image pair","Client adaptation","Artboard"]},
  {id:"M10",name:"Campaign score",family:"Lookbook / Campaign",scope:"page-capable",typography:["poster","brutalist","playful","poster"],art:"billboard",dna:"Overscale chapter words alternate with edge-to-edge photographic bands and small counter-images, building a campaign as a graphic score.",count:[3,6],ratios:"Wide primary crops, contained secondary images",content:"Three to six short chapter phrases and a narrative line per image.",media:"3–6 campaign photographs with safe central crop and full-image companion.",mobile:"Type becomes two-line phrases above a taller image band; a small full-image plate preserves what the dramatic crop omits.",interaction:"Static chapter sequence; strong resting composition with no animation dependency.",motion:"Proposed: type masking and opposing image progression; no essential text hidden under reduced motion.",constraints:"Short campaign phrases required. No overlay navigation safe zone and no arbitrary large text payload.",controls:["Client adaptation","Artboard"]},
  {id:"M11",name:"Media cabinet",family:"Mixed Media",scope:"both",typography:["brutalist","technical","humanist","brutalist"],art:"precision",dna:"A working archive sorts mixed stills and motion records by subject, with large record numbers, format labels, notes and independent native playback.",count:[4,24],ratios:"Arbitrary source ratios; contained media",content:"Record title, category, format, note; transcript for video.",media:"4–24 image/video records; video requires poster, captions where speech exists and a descriptive transcript. Current fixture reel is a silent generated still-image sequence.",mobile:"Compact two-column records become full-width for video. Notes stay below each record and filters wrap.",interaction:"Subject filter buttons and native video controls; video preload none, no autoplay. Category switches unmount hidden video.",motion:"Only user-started video. Proposed: optional archive filtering reveal with no layout animation under reduced motion.",constraints:"No streaming provider integration. Production needs dedicated thumbnail sources, caption track schema and pagination.",controls:["Subject filter","Native playback","Client adaptation","Artboard"]},
  {id:"M12",name:"Light table",family:"Mixed Media",scope:"both",typography:["playful","humanist","neo-grotesk","technical"],art:"salon",dna:"Two independent viewing wells let a visitor pin unlike images side by side from a shared tray, supporting visual comparison without a matched-image wipe.",count:[3,16],ratios:"Mixed portrait, landscape, square; contain in separate wells",content:"Independent media titles and comparison notes; no implied before/after claim.",media:"3–16 still images, including uneven resolutions. No registration or identical-camera constraint.",mobile:"Two wells remain adjacent with captions below; tray becomes horizontally scrollable. Tap a well, then a source; no drag requirement.",interaction:"Choose left/right well, then choose source; named buttons, pressed state and live assignment status. Duplicates permitted for inspection.",motion:"Proposed: subtle selection outline and instant-to-short dissolve; no magnetic cursor dependency.",constraints:"Images only in this study. Cross-video synchronization and annotation persistence are deferred.",controls:["Active well","Media assignment","Client adaptation","Artboard"]},
  {id:"M13",name:"Viewport gallery",family:"Gallery / Photography",scope:"page-capable",typography:["neo-grotesk","technical","humanist","neo-grotesk"],art:"precision",dna:"A compact navbar sits directly above a full-width, gapless two-column image grid. Desktop rows occupy the remaining viewport height; phone rows are shorter so four pieces fit below the navbar. Additional images create more rows. A floating panel reveals the item title and details over the lower half.",count:[1,24],ratios:"Mixed media ratios; full silhouettes contained for the authored studio apparel plates",content:"Image, title, category and short detail for every tile.",media:"1–24 still photographs. Odd final counts leave an honest empty second cell; no filler or duplicate imagery.",mobile:"Two columns remain at every width; phone row heights fit two rows in the available viewport. Navbar wraps into two compact rows; tap a tile to toggle its detail panel. Details use compact readable type.",interaction:"Hover or keyboard focus reveals details. Click / tap pins or closes details; Escape dismisses. Navbar categories filter the visible pieces.",motion:"Immediate reveal; no animation dependency or automatic movement.",constraints:"Viewport height comes from the host (100svh by default; explicit artboard height inside Lab). This is editorial browsing, not a cart or product-detail route. Longer detail copy is bounded inside its panel.",controls:["Category filter","Tile details","Client adaptation","Artboard"]},
];
/** Proposal bridge uses engine vocabulary without registering unapproved study renderers. */
export function studyContract(s: MediaStudy): SectionContract {
  return { category:"portfolio", contentSchema:`study005.${s.id}.content`,mediaSchema:`study005.${s.id}.media`,structuralDNA:s.dna,variants:["authored"],typography:{profiles:s.typography,roles:["display","heading","body","accent","mono"],behavior:"Four authored client profiles demonstrated; unrestricted profile overrides are not implemented."},artDirections:[s.art],artBehavior:"Authored spatial direction is invariant in this creative study.",motionIntensities:["none"],motion:["none"],overrides:[],media:{geometries:s.id === "M02" || s.id === "M10" ? ["panorama","contained"] : s.id === "M08" ? ["portrait-emphasis","contained"] : ["contained"],tones:["natural"]},icons:[],compatibility:{},responsive:{desktop:s.dna,tablet:"Contracted margins; preserve mechanism and source order.",mobile:s.mobile,readingOrder:["section title","media records in source order","captions and controls"]},accessibility:{landmark:"section",heading:"h2",keyboard:s.interaction,reducedMotion:"No automatic animation, autoplay or smooth scroll. Media remains visible.",contrast:"Opaque caption surfaces; inherited foreground/background tested separately from photography."} };
}
export function validateStudyBrief(s: MediaStudy, b: MediaBrief): string[] {
  const issues:string[]=[];
  if(b.items.length<s.count[0]||b.items.length>s.count[1])issues.push(`Requires ${s.count[0]}–${s.count[1]} media items.`);
  if(s.id==="M09" && b.items.length%2)issues.push("Look / closer requires complete authored pairs.");
  if(new Set(b.items.map(i=>i.id)).size!==b.items.length)issues.push("Media IDs must be unique.");
  for(const item of b.items){if(!item.alt.trim()||!item.title.trim()||!item.src||item.width<=0||item.height<=0)issues.push(`Incomplete media: ${item.id}`);if(item.kind==="video"&&(s.id!=="M11"||!item.poster||!item.transcript))issues.push(`Video ${item.id} requires a cabinet poster and transcript.`);}
  return issues;
}
